### PR TITLE
Save LOI name dialog state on the view model to prevent re-triggering the LOI name dialog.

### LINKED ISSUE #2310: [Draw an area] App crashes on secondary (non-LOI) geometry tasks when offline
On Pixel 7 physical device in Airplane Mode, as a normal data collection task while adding an LOI. Does not occur when connected:

```
Fatal Exception: com.google.android.gms.common.api.ApiException: 8502: SETTINGS_CHANGE_UNAVAILABLE
       at com.google.android.gms.common.internal.ApiExceptionUtil.fromStatus(com.google.android.gms:play-services-base@@18.1.0:3)
       at com.google.android.gms.common.api.internal.TaskUtil.setResultOrApiException(com.google.android.gms:play-services-base@@18.1.0:4)
       at com.google.android.gms.internal.location.zzcq.zzb(com.google.android.gms:play-services-location@@21.0.1:2)
       at com.google.android.gms.internal.location.zzr.zza(com.google.android.gms:play-services-location@@21.0.1:3)
       at com.google.android.gms.internal.location.zzb.onTransact(com.google.android.gms:play-services-location@@21.0.1:3)
       at android.os.Binder.execTransactInternal(Binder.java:1501)
       at android.os.Binder.execTransact(Binder.java:1440)
```

### LINKED ISSUE #2331: [LOI] New LOI name dialog is triggered N times when pressing back after drawing an area with N vertices.
**Describe the bug**
The new LOI name dialog introduced in https://github.com/google/ground-android/pull/2321 gets retriggered N times when pressing "Previous" after drawing N vertices then undoing all of them.

**To Reproduce**
1. Create an ad-hoc survey a draw point, draw area, and capture location tasks.
2. Get to the draw area task and create a polygon with 3 vertices and complete.
3. Press undo until the "Previous" button is shown.
4. Press "Previous", see that the dialog is triggered 3 times.

**Expected behavior**
Dialog should only appear after the LOI task. Should only be retriggered if you go back to the LOI task then hit Next again.

**Actual behavior**
LOI Name dialog is triggered many times.

**Screenshots**
Screenshot 2024-03-11 at 4 09 32 PM

### PR DESCRIPTION
**Pull request by sufyanAbbasi**
Fixes #2331

Prevent re-triggering the LOI name dialog when clicking Previous (which recomposes the Composable) by saving the dialog open state on the view model. Also performs some refactoring to adhere to Jetpack State Hoisting architecture.

- [x] Add new mutable state to the view model to keep track of whether to open the dialog on each compose.
- [x] Refactor to use `rememberSaveable` for better save state management.
- [x] Broke up the `Pair<String, Boolean>` into two different `rememberSaveables`.

- [x] Followed repro case from the bug. Breakpoint on the recompose  step to verify that the boolean state is preserved.

PTAL @gino-m!

### CODE REVIEW

File: ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/AbstractTaskFragment.kt [hunk 1]
```diff
@@ -217,28 +219,40 @@ abstract class AbstractTaskFragment<T : AbstractTaskViewModel> : AbstractFragmen
...
           }
         }
-      }
-    )
+      )
+    }
+  }
+
+  @Composable
+  fun ShowLoiNameDialog(initialNameValue: String, onNameSet: (String) -> Unit) {
```
Comment (gino-m) [inline ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/AbstractTaskFragment.kt:239]: Pity we don't have a `GeometryTaskFragment`, since `AbstractTaskFragment` is used by all tasks.

**Review by gino-m — APPROVED** [review]
👍 Nice fix!
