### PR TITLE
[View/add/edit observations] Sort fields by `index` defined in form

### LINKED ISSUE #396: [View/edit observation] Order of fields not consistent
**To Reproduce**
1. Select "Plastic Frog Finder" project
2. Click on "+" to add observation

**Expected behavior**
Photo field should be at the last 

**Actual behavior**
Photo field is at position 3 

**Screenshots**
image

### PR DESCRIPTION
**Pull request by gino-m**
Fixes #396.

### CODE REVIEW

File: gnd/src/main/java/com/google/android/gnd/model/form/Form.java [hunk 1]
```diff
@@ -35,6 +37,12 @@
 
   public abstract ImmutableList<Element> getElements();
 
+  public ImmutableList<Element> getElementsSorted() {
```
Comment (shobhitagarwal1612) [inline gnd/src/main/java/com/google/android/gnd/model/form/Form.java:40]: How about `getElementsSorted()` --> `getSortedElements()`?

File: gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/FieldEntity.java [hunk 2]
```diff
@@ -52,6 +52,11 @@
   @ColumnInfo(name = "id")
   public abstract String getId();
 
+  @CopyAnnotations
+  @Nullable
+  @ColumnInfo(name = "index")
+  public abstract Integer getIndex();
```
Comment (shobhitagarwal1612) [inline gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/FieldEntity.java:58]: Can we please make this `@NonNull`? It would remove the extra complexity of having to deal with all fallbacks

File: gnd/src/main/java/com/google/android/gnd/model/form/Element.java [hunk 3]
```diff
@@ -30,6 +31,21 @@
...
+      case FIELD:
+        // Fall back to hash code id on missing index; the order won't necessarily be correct
+        // but at least it will be stable.
+        return Optional.ofNullable(getField().getIndex())
+            .orElseGet(() -> getField().getId().hashCode());
+      case UNKNOWN:
+        // Intentional fall-through.
+      default:
+        // Fall back for unknown / bad index.
+        return hashCode();
```
Comment (shobhitagarwal1612) [inline gnd/src/main/java/com/google/android/gnd/model/form/Element.java:45]: What if we make index a required field? If the online form generator always adds an index then there would be no need to take care of adding this attribute manually. Wdyt?

File: gnd/src/main/java/com/google/android/gnd/model/form/Form.java (hunk 1 above)
Comment (gino-m) [reply gnd/src/main/java/com/google/android/gnd/model/form/Form.java:40]: The naming was chosen to emphasize that this is a variant of the `getElements()` method -  it also returns elements, but sorted. I've seen this naming convention used elsewhere but can't find it now. I don't feel strongly about it though. Is there precedency for this pattern that you know of?

File: gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/FieldEntity.java (hunk 2 above)
Comment (gino-m) [reply gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/FieldEntity.java:58]: Done!

File: gnd/src/main/java/com/google/android/gnd/model/form/Form.java (hunk 1 above)
Comment (shobhitagarwal1612) [reply gnd/src/main/java/com/google/android/gnd/model/form/Form.java:40]: I don't know if there is a rule/pattern for that. It just seemed much more natural to add "sorted" first. I am fine with either as it is just a minor nit. Let's keep it the same way.

File: gnd/src/main/java/com/google/android/gnd/model/form/Element.java (hunk 3 above)
Comment (gino-m) [reply gnd/src/main/java/com/google/android/gnd/model/form/Element.java]: Good idea. Let's handle missing `index` in remote closer to the source: eff2520c74fd4db0ac66837d5479965f1b9c40ef.

**Comment by gino-m** [comment]
Thanks @shobhitagarwal1612, RFAL!

**Review by shobhitagarwal1612 — APPROVED** [review]
Thanks for the fix!

**Comment by gino-m** [comment]
Working now, thanks for the help! 🚀

**Review by shobhitagarwal1612 — APPROVED** [review]
