### PR TITLE
Error Handling for urlConnection

### LINKED ISSUE #2683: App Crash - While Downloading Area
**Describe the bug**
Unusual crash, as this is not because of the app, but more of a third party. Need to figure out how we can prevent such cases.

```
Process: com.google.android.ground, PID: 16770
java.net.SocketTimeoutException: timeout
at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:214)
at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:263)
at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:217)
at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:307)
at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:301)
at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:197)
at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
at com.google.android.ground.ui.map.gms.mog.UrlInputStream.openStream(UrlInputStream.kt:47)
at com.google.android.ground.ui.map.gms.mog.UrlInputStream.<init>(UrlInputStream.kt:36)
at com.google.android.ground.ui.map.gms.mog.MogClient$getTiles$2.invokeSuspend(MogClient.kt:118)
at com.google.android.ground.ui.map.gms.mog.MogClient$getTiles$2.invoke(Unknown Source:8)
at com.google.android.ground.ui.map.gms.mog.MogClient$getTiles$2.invoke(Unknown Source:4)
at kotlinx.coroutines.flow.SafeFlow.collectSafely(Builders.kt:61)
at kotlinx.coroutines.flow.AbstractFlow.collect(Flow.kt:230)
at kotlinx.coroutines.flow.FlowKt__CollectKt.emitAll(Collect.kt:109)
at kotlinx.coroutines.flow.FlowKt.emitAll(Unknown Source:1)
at com.google.android.ground.ui.map.gms.mog.MogClient$getTiles$1.invokeSuspend(MogClient.kt:109)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c510a87, Dispatchers.IO]
Caused by: java.net.SocketException: socket is closed
at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(:com.google.android.gms@243136038@24.31.36 (190400-661292151):15)
at com.android.okhttp.okio.Okio$2.read(Okio.java:138)
at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:213)
... 30 more
2024-08-22 12:57:44.618 16770-17415 JavaUrlRequest          com.google.android.ground            E  Exception when closing OutputChannel (Ask Gemini)
java.net.ProtocolException: unexpected end of stream
at com.android.okhttp.internal.http.Http1xStream$FixedLengthSink.close(Http1xStream.java:302)
at com.android.okhttp.okio.RealBufferedSink.close(RealBufferedSink.java:242)
at com.android.okhttp.okio.RealBufferedSink$1.close(RealBufferedSink.java:210)
at java.nio.channels.Channels$WritableByteChannelImpl.implCloseChannel(Channels.java:481)
at java.nio.channels.spi.AbstractInterruptibleChannel.close(AbstractInterruptibleChannel.java:113)
at org.chromium.net.impl.JavaUrlRequest$OutputStreamDataSink.k(:com.google.android.gms.policy_maps_core_dynamite@243125309@243125304042.661367323.661367323:17)
at org.chromium.net.impl.JavaUrlRequest$$ExternalSyntheticLambda10.run(:com.google.android.gms.policy_maps_core_dynamite@243125309@243125304042.661367323.661367323:9)
at org.chromium.net.impl.JavaUrlRequest$SerializingExecutor.a(:com.google.android.gms.policy_maps_core_dynamite@243125309@243125304042.661367323.661367323:30)
at org.chromium.net.impl.JavaUrlRequest$SerializingExecutor$$ExternalSyntheticLambda0.run(:com.google.android.gms.policy_maps_core_dynamite@243125309@243125304042.661367323.661367323:3)
at org.chromium.net.impl.JavaUrlRequest$$ExternalSyntheticLambda14.run(:com.google.android.gms.policy_maps_core_dynamite@243125309@243125304042.661367323.661367323:21)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
at org.chromium.net.impl.JavaCronetEngine$1$1.run(:com.google.android.gms.policy_maps_core_dynamite@243125309@243125304042.661367323.661367323:19)
at java.lang.Thread.run(Thread.java:1012)

```

**To Reproduce**
1. Go to Offline Imagary
2. Select a region and Download
3. See error

**Expected behavior**
App should not crash

**Actual behavior**
App Crash

### PR DESCRIPTION
**Pull request by anandwana001**
Fixes #2683 
Fixes https://github.com/google/ground-android/issues/662

@shobhitagarwal1612  PTAL?

### CODE REVIEW

File: ground/src/main/java/com/google/android/ground/ui/map/gms/mog/UrlInputStream.kt [hunk 1]
```diff
@@ -38,19 +39,25 @@ class UrlInputStream(private val url: String, private val byteRange: LongRange?
...
+      val responseCode = urlConnection.responseCode
+      if (responseCode == 404) throw FileNotFoundException("$url not found")
+      val expectedResponseCode = if (byteRange == null) 200 else 206
+      if (responseCode != expectedResponseCode) {
+        throw IOException("HTTP $responseCode accessing $url")
+      }
+      return urlConnection.inputStream
+    } catch (e: Exception) {
+      urlConnection.disconnect()
+      error("Attempt Failed with $e")
```
Comment (shobhitagarwal1612) [inline ground/src/main/java/com/google/android/ground/ui/map/gms/mog/UrlInputStream.kt:59]: Won't this throw another exception? How are we planning to handle the timeouts?

Comment (anandwana001) [reply ground/src/main/java/com/google/android/ground/ui/map/gms/mog/UrlInputStream.kt:59]: 1. As for this pr, the idea is to get logs
2. Added connectTimeout
3. for timeout, or any other failure, it should wrap the failure and return - a part of https://github.com/google/ground-android/issues/2891

**Review by gino-m — CHANGES_REQUESTED** [review]

File: ground/src/main/java/com/google/android/ground/ui/map/gms/mog/UrlInputStream.kt (hunk 1 above)
Comment (anandwana001) [reply ground/src/main/java/com/google/android/ground/ui/map/gms/mog/UrlInputStream.kt:59]: > Why do we need urlConnection.disconnect()? What happens if that call fails?

For releasing the resources and not waiting for the garbage collection to clean it, hence doing it ourselves.
https://developer.android.com/reference/java/net/HttpURLConnection#disconnect()

Comment (gino-m) [reply ground/src/main/java/com/google/android/ground/ui/map/gms/mog/UrlInputStream.kt:59]: To your question(s):

* The `catch` block catches the exceptions explicitly thrown in the `try` block, as well as anything else thrown by functions called inside the `try` block. 
* Calling `error()` swallows throws an `IllegalStateException`, in this case with the original error in stack trace packed inside that exceptions `message`.
* If the intent of the `catch` block is to close the connection on error, and that it will be up to the caller to log exceptions, you should just `throw e` instead to allow that to happen.
* If instead the intention is for this method to handle all exceptions, then we should log the error with `Timber.d` and return a failure state.

More generally, we should be consistent about who is responsible for closing the connection. Since the caller will need to close the connection once they've consumed the stream, then closing the connection should be done there.

**Comment by gino-m** [comment]
We should handle the error upstream where it can actually be addressed:

https://github.com/google/ground-android/blob/9ef90adb6cc8aade4bd87350fe820fd8c0a23ace/ground/src/main/java/com/google/android/ground/ui/offlineareas/selector/OfflineAreaSelectorViewModel.kt#L100-L113

File: ground/src/main/java/com/google/android/ground/ui/offlineareas/selector/OfflineAreaSelectorViewModel.kt [hunk 2]
```diff
@@ -98,15 +100,21 @@ internal constructor(
...
-        downloadProgress.postValue(progressValue)
-      }
+      offlineAreaRepository
+        .downloadTiles(viewport!!)
+        .catch {
+          isFailure.postValue(true)
+          isDownloadProgressVisible.postValue(false)
+        }
+        .collect { (bytesDownloaded, totalBytes) ->
+          val progressValue =
```
Comment (gino-m) [inline ground/src/main/java/com/google/android/ground/ui/offlineareas/selector/OfflineAreaSelectorViewModel.kt:110]: Could you please refactor the logic in this lambda into its own function while you're at it?

File: ground/src/main/res/values-es/strings.xml [hunk 3]
```diff
@@ -52,6 +52,7 @@
   <string name="settings">Configuración</string>
   <string name="offline_area_viewer_title">Área descargada</string>
   <string name="offline_area_viewer_remove_button">Eliminar del dispositivo</string>
+  <string name="offline_area_download_error">¡Error de descarga! por favor inténtalo de nuevo</string>
```
Comment (gino-m) [inline ground/src/main/res/values-es/strings.xml:55]: Please capitalize "p" in "por favor", replace "!" with "."

File: ground/src/main/res/values-fr/strings.xml [hunk 4]
```diff
@@ -53,6 +53,7 @@
   <string name="settings">Paramètres</string>
   <string name="offline_area_viewer_title">Zone téléchargée</string>
   <string name="offline_area_viewer_remove_button">Supprimer de l&#8217;appareil</string>
+  <string name="offline_area_download_error">Échec du téléchargement ! Veuillez réessayer</string>
```
Comment (gino-m) [inline ground/src/main/res/values-fr/strings.xml:56]: Please replace " !" with "." (no preceding space)

File: ground/src/main/res/values/strings.xml [hunk 5]
```diff
@@ -53,6 +53,7 @@
   <string name="settings">Settings</string>
   <string name="offline_area_viewer_title">Downloaded area</string>
   <string name="offline_area_viewer_remove_button">Remove from device</string>
+  <string name="offline_area_download_error">Download Failed! Please Try Again</string>
```
Comment (gino-m) [inline ground/src/main/res/values/strings.xml:56]: Please use sentence case instead of title case:
"Download failed. Please try again"

File: ground/src/main/java/com/google/android/ground/ui/offlineareas/selector/OfflineAreaSelectorFragment.kt [hunk 6]
```diff
@@ -62,8 +66,17 @@ class OfflineAreaSelectorFragment : AbstractMapContainerFragment() {
 
   override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
     super.onViewCreated(view, savedInstanceState)
-    viewModel.isDownloadProgressVisible.observe(viewLifecycleOwner) {
-      showDownloadProgressDialog(it)
+    viewLifecycleOwner.lifecycleScope.launch {
```
Comment (gino-m) [inline ground/src/main/java/com/google/android/ground/ui/offlineareas/selector/OfflineAreaSelectorFragment.kt:69]: Can we add tests for this logic?

File: ground/src/main/java/com/google/android/ground/ui/offlineareas/selector/OfflineAreaSelectorViewModel.kt [hunk 7]
```diff
@@ -98,15 +100,21 @@ internal constructor(
...
-      offlineAreaRepository.downloadTiles(viewport!!).collect { (bytesDownloaded, totalBytes) ->
-        val progressValue =
-          if (totalBytes > 0) {
-            (bytesDownloaded.toFloat() / totalBytes.toFloat()).coerceIn(0f, 1f)
-          } else {
-            0f
-          }
-        downloadProgress.postValue(progressValue)
-      }
+      offlineAreaRepository
```
Comment (gino-m) [inline ground/src/main/java/com/google/android/ground/ui/offlineareas/selector/OfflineAreaSelectorViewModel.kt:103]: Can you also add tests for this logic as well?

**Review by gino-m — CHANGES_REQUESTED** [review]
Thanks! A few requests, LG

File: app/src/main/java/com/google/android/ground/ui/offlineareas/selector/OfflineAreaSelectorFragment.kt [hunk 8]
```diff
@@ -68,8 +71,17 @@ class OfflineAreaSelectorFragment : AbstractMapContainerFragment() {
 
   override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
     super.onViewCreated(view, savedInstanceState)
-    viewModel.isDownloadProgressVisible.observe(viewLifecycleOwner) {
-      showDownloadProgressDialog(it)
+    viewLifecycleOwner.lifecycleScope.launch {
+      repeatOnLifecycle(Lifecycle.State.RESUMED) {
```
Comment (shobhitagarwal1612) [inline app/src/main/java/com/google/android/ground/ui/offlineareas/selector/OfflineAreaSelectorFragment.kt:75]: Is this necessary? Can it be removed given that coroutines aren't getting suspended.

File: app/src/main/java/com/google/android/ground/ui/offlineareas/selector/OfflineAreaSelectorViewModel.kt [hunk 9]
```diff
@@ -100,20 +102,29 @@ internal constructor(
...
-            if (totalBytes > 0) {
-              (bytesDownloaded.toFloat() / totalBytes.toFloat()).coerceIn(0f, 1f)
-            } else {
-              0f
-            }
-          downloadProgress.postValue(progressValue)
+    downloadJob = viewModelScope.launch(ioDispatcher) {
+      offlineAreaRepository
+        .downloadTiles(viewport!!)
+        .catch {
```
Comment (shobhitagarwal1612) [inline app/src/main/java/com/google/android/ground/ui/offlineareas/selector/OfflineAreaSelectorViewModel.kt:108]: Can we log the exception to `timber`?

File: app/src/test/java/com/google/android/ground/ui/offlineareas/selector/OfflineAreaSelectorFragmentTest.kt [hunk 10]
```diff
@@ -125,4 +132,31 @@ class OfflineAreaSelectorFragmentTest : BaseHiltTest() {
 
     viewModel.downloadProgress.removeObserver(observer)
   }
+
+  @Test
+  fun `test failure case displays toast`() = runWithTestDispatcher {
+    val isFailureObserver = mock(Observer::class.java) as Observer<Boolean>
+    fragment.viewLifecycleOwner.lifecycleScope.launch {
+      viewModel.isFailure.observeForever(isFailureObserver)
+      viewModel.isFailure.postValue(true)
```
Comment (shobhitagarwal1612) [inline app/src/test/java/com/google/android/ground/ui/offlineareas/selector/OfflineAreaSelectorFragmentTest.kt:141]: Is it possible to call the download flow and mock the `downloadTiles` to throw an error?

Comment (anandwana001) [reply app/src/test/java/com/google/android/ground/ui/offlineareas/selector/OfflineAreaSelectorFragmentTest.kt:141]: let me try this in another pr

File: app/src/main/java/com/google/android/ground/ui/offlineareas/selector/OfflineAreaSelectorFragment.kt (hunk 8 above)
Comment (anandwana001) [reply app/src/main/java/com/google/android/ground/ui/offlineareas/selector/OfflineAreaSelectorFragment.kt:75]: ah, those are live data, fixed now

File: app/src/main/java/com/google/android/ground/ui/offlineareas/selector/OfflineAreaSelectorViewModel.kt (hunk 9 above)
Comment (anandwana001) [reply app/src/main/java/com/google/android/ground/ui/offlineareas/selector/OfflineAreaSelectorViewModel.kt:108]: sure

**Review by shobhitagarwal1612 — APPROVED** [review]
