### PR TITLE
Fix suggest loi cards not showing

### LINKED ISSUE #1880: "Collect data at new site" (suggest LOI) cards not showing
It looks like `suspend fun updateMapLois()` in `HomeScreenMapContainerViewModel` never actually returns, so `updateSuggestLoiJobs` is never called.

@shobhitagarwal1612 FYI.

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Fixes #1880

https://github.com/google/ground-android/assets/8918023/436071be-26bd-4b67-a194-55de22bb72ec

@gino-m  PTAL?

### CODE REVIEW

File: ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerViewModel.kt [hunk 1]
```diff
@@ -70,91 +71,69 @@ internal constructor(
...
-      _suggestLoiJobs.value = listOf()
-    } else {
-      _suggestLoiJobs.value = survey.jobs.filter { it.suggestLoiTaskType != null }.toList()
-    }
+    val isZoomedInFlow =
+      getCurrentCameraPosition().mapNotNull { it.zoomLevel }.map { it >= CLUSTERING_ZOOM_THRESHOLD }
+
+    loisInViewport =
+      activeSurvey
+        .combine(isZoomedInFlow) { a, b -> Pair(a, b) }
```
Comment (JSunde) [inline ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerViewModel.kt:114]: Can you update the names from `a, b` here to `survey, isZoomedIn`?

File: ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerViewModel.kt [hunk 2]
```diff
@@ -70,91 +71,69 @@ internal constructor(
...
+        .flatMapLatest { (survey, isZoomedIn) ->
+          val bounds = currentCameraPosition.value?.bounds
+          if (bounds == null || survey == null || !isZoomedIn) flowOf(listOf())
+          else loiRepository.getWithinBoundsOnceAndStream(survey, bounds).asFlow()
+        }
+
+    suggestLoiJobs =
+      activeSurvey
+        .combine(isZoomedInFlow) { a, b -> Pair(a, b) }
```
Comment (JSunde) [inline ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/HomeScreenMapContainerViewModel.kt:123]: ditto

**Review by JSunde — APPROVED** [review]
