### PR TITLE
Handle Empty Coordinate List in centerOrError() with Safe Default

### LINKED ISSUE #3338: Application crashes when loading/processing Invalid Geometry
The application should handle the invalid geometry

Here is the stacktrace:

```
2025-10-27 13:37:07.932 25609-25609 AndroidRuntime          org.openforis.ground                 E  FATAL EXCEPTION: main
                                                                                                    Process: org.openforis.ground, PID: 25609
                                                                                                    java.lang.IllegalStateException: missing vertices
                                                                                                        at org.groundplatform.android.model.geometry.GeometryKt.centerOrError(Geometry.kt:172)
                                                                                                        at org.groundplatform.android.model.geometry.GeometryKt.access$centerOrError(Geometry.kt:1)
                                                                                                        at org.groundplatform.android.model.geometry.LinearRing.center(Geometry.kt:121)
                                                                                                        at org.groundplatform.android.model.geometry.Polygon.center(Geometry.kt:58)
                                                                                                        at org.groundplatform.android.ui.map.gms.features.FeatureClusterItem.getPosition(FeatureClusterItem.kt:25)
                                                                                                        at com.google.maps.android.clustering.algo.NonHierarchicalDistanceBasedAlgorithm$QuadItem.<init>(NonHierarchicalDistanceBasedAlgorithm.java:270)
                                                                                                        at com.google.maps.android.clustering.algo.NonHierarchicalDistanceBasedAlgorithm$QuadItem.<init>(NonHierarchicalDistanceBasedAlgorithm.java:262)
                                                                                                        at com.google.maps.android.clustering.algo.NonHierarchicalDistanceBasedAlgorithm.addItem(NonHierarchicalDistanceBasedAlgorithm.java:73)
                                                                                                        at com.google.maps.android.clustering.algo.PreCachingAlgorithmDecorator.addItem(PreCachingAlgorithmDecorator.java:48)
                                                                                                        at com.google.maps.android.clustering.algo.ScreenBasedAlgorithmAdapter.addItem(ScreenBasedAlgorithmAdapter.java:41)
                                                                                                        at com.google.maps.android.clustering.ClusterManager.addItem(ClusterManager.java:202)
                                                                                                        at org.groundplatform.android.ui.map.gms.features.FeatureClusterManager.addFeature(FeatureClusterManager.kt:50)
                                                                                                        at org.groundplatform.android.ui.map.gms.features.FeatureManager.add(FeatureManager.kt:124)
                                                                                                        at org.groundplatform.android.ui.map.gms.features.FeatureManager.setFeatures(FeatureManager.kt:102)
                                                                                                        at org.groundplatform.android.ui.map.gms.GoogleMapsFragment.setFeatures(GoogleMapsFragment.kt:249)
                                                                                                        at org.groundplatform.android.ui.home.mapcontainer.HomeScreenMapContainerFragment.onMapReady$lambda$0(HomeScreenMapContainerFragment.kt:253)
                                                                                                        at org.groundplatform.android.ui.home.mapcontainer.HomeScreenMapContainerFragment.$r8$lambda$eTceKHe9XlRF6bjVSv5I4ZTE63g(Unknown Source:0)
                                                                                                        at org.groundplatform.android.ui.home.mapcontainer.HomeScreenMapContainerFragment$$ExternalSyntheticLambda2.invoke(D8$$SyntheticClass:0)
                                                                                                        at org.groundplatform.android.ui.common.AbstractFragment$launchWhenStartedAndCollect$1$1.emit(AbstractFragment.kt:143)
                                                                                                        at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:33)
                                                                                                        at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
                                                                                                        at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:14)
                                                                                                        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
                                                                                                        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
                                                                                                        at kotlinx.coroutines.EventLoop.processUnconfinedEvent(EventLoop.common.kt:65)
                                                                                                        at kotlinx.coroutines.DispatchedTaskKt.resumeUnconfined(DispatchedTask.kt:243)
                                                                                                        at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:147)
                                                                                                        at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:470)
                                                                                                        at kotlinx.coroutines.CancellableContinuationImpl.completeResume(CancellableContinuationImpl.kt:591)
                                                                                                        at kotlinx.coroutines.selects.SelectKt.tryResume(Select.kt:870)
                                                                                                        at kotlinx.coroutines.selects.SelectKt.access$tryResume(Select.kt:1)
                                                                                                        at kotlinx.coroutines.selects.SelectImplementation.trySelectInternal(Select.kt:647)
                                                                                                        at kotlinx.coroutines.selects.SelectImplementation.trySelect(Select.kt:624)
                                                                                                        at kotlinx.coroutines.selects.OnTimeout.register$lambda$0(OnTimeout.kt:53)
                                                                                                        at kotlinx.coroutines.selects.OnTimeout.$r8$lambda$XnMkStofq3IwGIgiwxayHvL9sM8(Unknown Source:0)
                                                                                                        at kotlinx.coroutines.selects.OnTimeout$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
                                                                                                        at android.os.Handler.handleCallback(Handler.java:995)
                                                                                                        at android.os.Handler.dispatchMessage(Handler.java:105)
                                                                                                        at android.os.Looper.loopOnce(Looper.java:288)
                                                                                                        at android.os.Looper.loop(Looper.java:393)
                                                                                                        at android.app.ActivityThread.main(ActivityThread.java:9564)
2025-10-27 13:37:07.933 25609-25609 AndroidRuntime          org.openforis.ground                 E      at java.lang.reflect.Method.invoke(Native Method)
                                                                                                        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:600)
                                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1010)
                                                                                                        Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@7d2d5cd, Dispatchers.Main.immediate]

```

### PR DESCRIPTION
**Pull request by anandwana001**
Fixes #3338 

This PR improves the centerOrError() extension function by safely handling empty or null coordinate lists.

Changes Made

Added a check using takeIf { it.isNotEmpty() } to avoid processing empty lists.

Replaced the hard error (error("missing vertices")) with a safe default return value Coordinates(0.0, 0.0) to prevent crashes.

Why This Change

Prevents runtime crashes when vertices are missing or empty.

Ensures consistent behavior by returning a neutral coordinate instead of throwing an exception.

Impact

Improves app stability during geometry or map operations where coordinate data might be incomplete.

@shobhitagarwal1612  PTAL?

### CODE REVIEW

**Comment by shobhitagarwal1612** [comment]
Please use a better issue title and update description to explain the changes being made and how are the changes verified. Thanks!

File: app/src/main/java/org/groundplatform/android/model/geometry/Geometry.kt [hunk 1]
```diff
@@ -163,10 +163,11 @@ data class LinearRing(val coordinates: List<Coordinates>) : Geometry {
...
- * Returns the center coordinates of the bounding box from the given list of coordinates.
+ * Returns the center coordinates of the bounding box from the given list of coordinates. Returns
+ * Coordinates(0.0, 0.0) if the list is null or empty.
  *
  * Note: This might return an unexpected result for oddly shaped polygons. Check if this can be
  * replaced with a centroid. See (#1737) for more info.
  */
 private fun List<Coordinates>?.centerOrError(): Coordinates =
-  this?.map { Point(it) }?.toBounds()?.center() ?: error("missing vertices")
+  this?.takeIf { it.isNotEmpty() }?.map { Point(it) }?.toBounds()?.center() ?: Coordinates(0.0, 0.0)
```
Comment (shobhitagarwal1612) [inline app/src/main/java/org/groundplatform/android/model/geometry/Geometry.kt]: The method was called centerOrError() to denote that it doesn't use default. Please either handle this at the calling site or rename the method to be more accurate.

File: app/src/main/java/org/groundplatform/android/ui/map/gms/features/FeatureManager.kt [hunk 2]
```diff
@@ -115,13 +115,14 @@ constructor(
...
-   * zoom level.
+   * zoom level. Empty geometries are not added to the cluster manager to avoid errors when
+   * calculating cluster positions.
    */
   private fun add(feature: Feature) =
     with(feature) {
       features.add(this)
       featuresByTag[tag] = this
-      if (clusterable) clusterManager.addFeature(this)
+      if (clusterable && !geometry.isEmpty()) clusterManager.addFeature(this)
```
Comment (shobhitagarwal1612) [inline app/src/main/java/org/groundplatform/android/ui/map/gms/features/FeatureManager.kt]: This should never even reach this location if the geometry is missing.

**Comment by shobhitagarwal1612** [comment]
Please let me know if this is ready to be re-reviewed.

**Comment by shobhitagarwal1612** [comment]
I took a closer look at the bug and was able to reproduce it locally. 

Here is a sample map feature which is causing the failure:
```
Feature(tag=Tag(id=7opzkfYGqg5UG0frjutm, type=LOCATION_OF_INTEREST), geometry=Polygon(shell=LinearRing(coordinates=[]), holes=[]), style=Style(color=-820190, vertexStyle=NONE), clusterable=true, selected=false, flag=true, tooltipText=null)
```

Instead of silently consuming the error, I would suggest updating `getValidLois` in LOIRepository to filter out these LOIs with empty coordinate list to mitigate the crash. This would not only solve the problem in the homescreen but everywhere else too which relies on reading valid LOIs from local storage.

However, this is not enough as we need to find the root cause as well. For that, I would suggest adding a check when saving these LOIs locally to throw an exception when attempting to save such empty coordinate LOIs. 

My hunch is that the app is reaching this invalid state during polygon drawing task but not exactly sure how.

@gino-m cc

File: app/src/main/java/org/groundplatform/android/data/local/room/stores/RoomLocationOfInterestStore.kt [hunk 3]
```diff
@@ -48,9 +53,26 @@ class RoomLocationOfInterestStore @Inject internal constructor() : LocalLocation
...
+      .map { lois ->
+        // Filter out LOIs with invalid/empty geometries to prevent crashes
+        lois
+          .filter { loi ->
+            val isValid =
+              when (val geometry = loi.geometry) {
+                is Polygon -> geometry.shell.coordinates.isNotEmpty()
+                is MultiPolygon -> geometry.polygons.all { it.shell.coordinates.isNotEmpty() }
+                else -> true // Point, LineString, LinearRing are always valid if they exist
+              }
```
Comment (shobhitagarwal1612) [inline app/src/main/java/org/groundplatform/android/data/local/room/stores/RoomLocationOfInterestStore.kt]: Let's add `isValid()` method to `Geometry` class and override it for each type of geometry. That would keep the core logic within the specific geometry implementation class

File: app/src/main/java/org/groundplatform/android/data/local/room/stores/RoomLocationOfInterestStore.kt [hunk 4]
```diff
@@ -48,9 +53,26 @@ class RoomLocationOfInterestStore @Inject internal constructor() : LocalLocation
...
-    locationOfInterestDao.getByDeletionState(survey.id, EntityDeletionState.DEFAULT).map {
-      toLocationsOfInterest(survey, it)
-    }
+    locationOfInterestDao
+      .getByDeletionState(survey.id, EntityDeletionState.DEFAULT)
+      .map { toLocationsOfInterest(survey, it) }
+      .map { lois ->
+        // Filter out LOIs with invalid/empty geometries to prevent crashes
+        lois
+          .filter { loi ->
```
Comment (shobhitagarwal1612) [inline app/src/main/java/org/groundplatform/android/data/local/room/stores/RoomLocationOfInterestStore.kt]: Let's move this filter to LOIRepository instead. The purpose of Room*Store is to fetch data from local storage only.

File: app/src/main/java/org/groundplatform/android/data/local/room/stores/RoomLocationOfInterestStore.kt [hunk 5]
```diff
@@ -61,6 +83,25 @@ class RoomLocationOfInterestStore @Inject internal constructor() : LocalLocation
   // TODO: Apply pending local mutations before saving.
   // Issue URL: https://github.com/google/ground-android/issues/706
   override suspend fun merge(model: LocationOfInterest) {
```
Comment (shobhitagarwal1612) [inline app/src/main/java/org/groundplatform/android/data/local/room/stores/RoomLocationOfInterestStore.kt:63]: Same as previous comment throughout the class

**Review by shobhitagarwal1612 — CHANGES_REQUESTED** [review]

File: app/src/main/java/org/groundplatform/android/model/geometry/Geometry.kt [hunk 6]
```diff
@@ -41,6 +41,9 @@ sealed interface Geometry {
   fun validate() {
     // default no-op implementation
   }
+
+  /** Returns true if the geometry is valid and has non-empty coordinates. */
+  fun isValid(): Boolean = true
```
Comment (shobhitagarwal1612) [inline app/src/main/java/org/groundplatform/android/model/geometry/Geometry.kt]: Let's remove the default value from this method.

File: app/src/main/java/org/groundplatform/android/model/geometry/Geometry.kt [hunk 7]
```diff
@@ -59,6 +62,8 @@ data class Polygon(val shell: LinearRing, val holes: List<LinearRing> = listOf()
 
   override fun isEmpty() = shell.isEmpty()
 
+  override fun isValid(): Boolean = shell.coordinates.isNotEmpty()
```
Comment (shobhitagarwal1612) [inline app/src/main/java/org/groundplatform/android/model/geometry/Geometry.kt]: QQ: The definition of `isValid()` seems to be `!isEmpty()`. It means that we can use `isEmpty` directly instead of introducing a new method for all geometry

File: app/src/main/java/org/groundplatform/android/data/local/room/stores/RoomLocationOfInterestStore.kt [hunk 8]
```diff
@@ -126,8 +126,10 @@ class RoomLocationOfInterestStore @Inject internal constructor() : LocalLocation
   ): List<LocationOfInterestMutationEntity> =
     locationOfInterestMutationDao.getMutations(id, *states)
 
-  override suspend fun insertOrUpdate(loi: LocationOfInterest) =
+  override suspend fun insertOrUpdate(loi: LocationOfInterest) {
+    require(!loi.geometry.isEmpty()) { "Cannot save LOI with invalid geometry" }
```
Comment (shobhitagarwal1612) [inline app/src/main/java/org/groundplatform/android/data/local/room/stores/RoomLocationOfInterestStore.kt]: Nit: replace "invalid" -> "empty"

File: app/src/main/java/org/groundplatform/android/model/geometry/Geometry.kt
Comment (shobhitagarwal1612) [inline app/src/main/java/org/groundplatform/android/model/geometry/Geometry.kt:1]: Please revert these changes. It would lead to bad states in the app instead of crashing the app which is not ideal either.

File: app/src/main/java/org/groundplatform/android/repository/LocationOfInterestRepository.kt [hunk 9]
```diff
@@ -100,11 +102,37 @@ constructor(
...
+      is MultiPolygon -> {
+        require(geometry.polygons.all { it.shell.coordinates.isNotEmpty() }) {
+          "Attempted to save LOI ${loi.id} with empty MultiPolygon coordinates. LOI: $loi"
+        }
+      }
+
+      else -> {
+        // Point, LineString, LinearRing don't need empty coordinate validation
+      }
+    }
```
Comment (shobhitagarwal1612) [inline app/src/main/java/org/groundplatform/android/repository/LocationOfInterestRepository.kt]: Can this be simplified with a single `geometry.isEmpty()` check?

File: app/src/main/java/org/groundplatform/android/repository/LocationOfInterestRepository.kt [hunk 10]
```diff
@@ -153,6 +181,29 @@ constructor(
...
+          is MultiPolygon -> {
+            require(geometry.polygons.all { it.shell.coordinates.isNotEmpty() }) {
+              "Attempted to apply mutation with empty MultiPolygon coordinates. Mutation: $mutation"
+            }
+          }
+
+          else -> {
+            // Point, LineString, LinearRing don't need empty coordinate validation
+          }
+        }
```
Comment (shobhitagarwal1612) [inline app/src/main/java/org/groundplatform/android/repository/LocationOfInterestRepository.kt]: Same as previous comment

**Review by shobhitagarwal1612 — CHANGES_REQUESTED** [review]

**Review by shobhitagarwal1612 — APPROVED** [review]
The code looks good now! I would suggest verifying that the PR mitigates the issue that was earlier reported  before submitting this change. Also, please update the PR description.
