### PR TITLE
Reuse the logic for displaying the label for an LOI

### LINKED ISSUE #2046: Incorrect LocationOfInterest label in DataCollectionFragment
LocationOfInterest label in DataCollectionFragment should use the format described in:
https://github.com/google/ground-platform/issues/1242

### LINKED ISSUE #2291: [Data collection flow] Header doesn't show full label of LOI, only ID
For example, an LOI with only ID 5 shows as "5" rather than "Point 5" as on the card.

@shobhitagarwal1612 PTAL?

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Fixes #2046
Fixes #2291

Reuse the logic for displaying label for the LOI everywhere.

@gino-m  PTAL?

### CODE REVIEW

File: ground/src/main/java/com/google/android/ground/ui/common/LocationOfInterestHelper.kt [hunk 1]
```diff
@@ -17,46 +17,58 @@ package com.google.android.ground.ui.common
...
-    return caption.ifEmpty { getLocationOfInterestType(loi) }
+    return if (loiName.isNotEmpty() && loiId.isNotEmpty()) {
+      "$loiName ($loiId)"
+    } else if (loiName.isNotEmpty()) {
+      loiName
+    } else if (loiId.isNotEmpty()) {
+      "${loi.geometry.toType()} ($loiId)"
+    } else {
+      loi.geometry.toDefaultName()
+    }
```
Comment (anandwana001) [inline ground/src/main/java/com/google/android/ground/ui/common/LocationOfInterestHelper.kt:42]: how about going with `when`, the nesting of if else will keep growing in the future.

WDYT?

File: ground/src/main/java/com/google/android/ground/ui/common/LocationOfInterestHelper.kt [hunk 2]
```diff
@@ -17,46 +17,58 @@ package com.google.android.ground.ui.common
...
-      is LineString -> "LineString"
-      is LinearRing -> "LinearRing"
-      is MultiPolygon -> "MultiPolygon"
+  fun getJobName(loi: LocationOfInterest): String? = loi.job.name
+
+  fun getSubmissionsText(count: Int): String =
+    when (count) {
+      0 -> "No submissions"
+      1 -> "$count submission"
+      else -> "$count submissions"
```
Comment (anandwana001) [inline ground/src/main/java/com/google/android/ground/ui/common/LocationOfInterestHelper.kt:51]: how about bringing these hardcoded values from strings.xml, this way it will be more easy to modify in future.

Comment (shobhitagarwal1612) [reply ground/src/main/java/com/google/android/ground/ui/common/LocationOfInterestHelper.kt]: Thanks for the suggestion! Done

File: ground/src/main/java/com/google/android/ground/ui/common/LocationOfInterestHelper.kt (hunk 1 above)
Comment (shobhitagarwal1612) [reply ground/src/main/java/com/google/android/ground/ui/common/LocationOfInterestHelper.kt:42]: I'm not sure how to achieve that since `when` expects a statement or an expression.

Comment (anandwana001) [reply ground/src/main/java/com/google/android/ground/ui/common/LocationOfInterestHelper.kt:42]:
```
when {
        loiName.isNotEmpty() -> ...
        else -> ...
    }
```

This way we can use when, it's doable.

Comment (shobhitagarwal1612) [reply ground/src/main/java/com/google/android/ground/ui/common/LocationOfInterestHelper.kt]: Thanks! Done

**Review by anandwana001 — APPROVED** [review]

**Review by gino-m — APPROVED** [review]
Thanks for the fix!
