### PR TITLE
[Code health] Clean up and improve error logging

### LINKED ISSUE #2849: [Code health] Replace direct call to Crashlytics with `Timber.e`

### LINKED ISSUE #2850: [Code health] Add descriptive text to existing calls to `Timber.e`

### LINKED ISSUE #2851: [Survey sync] Never give up trying to sync survey metadata
Instead, keep trying until connection is available.

### LINKED ISSUE #2853: [Code health] FirebaseFirestoreException reported when upload photo offline
```
Photo upload failed. local path: /storage/emulated/0/Android/data/org.openforis.ground/files/Pictures/EE4McCRO9ODc6qLKD8g0-OCEr7W7mQ8n0HmH75caE.jpg, remote path: user-media/surveys/98uFH4ZTT6h2I2KinWCe/submissions/EE4McCRO9ODc6qLKD8g0-OCEr7W7mQ8n0HmH75caE.jpg

      Non-fatal Exception: com.google.firebase.firestore.FirebaseFirestoreException: Failed to get document because the client is offline.
       at com.google.firebase.firestore.DocumentReference.lambda$getViaSnapshotListener$1(DocumentReference.java:331)
       at com.google.firebase.firestore.DocumentReference$$ExternalSyntheticLambda2.onEvent(D8$$SyntheticClass)
       at com.google.firebase.firestore.DocumentReference.lambda$addSnapshotListenerInternal$2$com-google-firebase-firestore-DocumentReference(DocumentReference.java:526)
       at com.google.firebase.firestore.DocumentReference$$ExternalSyntheticLambda1.onEvent(D8$$SyntheticClass)
       at com.google.firebase.firestore.core.AsyncEventListener.lambda$onEvent$0$com-google-firebase-firestore-core-AsyncEventListener(AsyncEventListener.java:42)
       at com.google.firebase.firestore.core.AsyncEventListener$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
       at androidx.credentials.CredentialManager$$ExternalSyntheticLambda0.execute(D8$$SyntheticClass)
       at com.google.firebase.firestore.core.AsyncEventListener.onEvent(AsyncEventListener.java:39)
       at com.google.firebase.firestore.core.QueryListener.raiseInitialEvent(QueryListener.java:196)
       at com.google.firebase.firestore.core.QueryListener.onOnlineStateChanged(QueryListener.java:127)
       at com.google.firebase.firestore.core.EventManager.handleOnlineStateChange(EventManager.java:259)
       at com.google.firebase.firestore.core.SyncEngine.handleOnlineStateChange(SyncEngine.java:422)
       at com.google.firebase.firestore.core.MemoryComponentProvider$RemoteStoreCallback.handleOnlineStateChange(MemoryComponentProvider.java:145)
       at com.google.firebase.firestore.remote.RemoteStore$$ExternalSyntheticLambda1.handleOnlineStateChange(D8$$SyntheticClass)
       at com.google.firebase.firestore.remote.OnlineStateTracker.setAndBroadcastState(OnlineStateTracker.java:181)
       at com.google.firebase.firestore.remote.OnlineStateTracker.lambda$handleWatchStreamStart$0$com-google-firebase-firestore-remote-OnlineStateTracker(OnlineStateTracker.java:121)
       at com.google.firebase.firestore.remote.OnlineStateTracker$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
       at com.google.firebase.firestore.util.AsyncQueue$DelayedTask.handleDelayElapsed(AsyncQueue.java:145)
       at com.google.firebase.firestore.util.AsyncQueue$DelayedTask.$r8$lambda$Ei7JopXmbThtDHIuNOab5jlUklU()
       at com.google.firebase.firestore.util.AsyncQueue$DelayedTask$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
       at java.util.concurrent.FutureTask.run(FutureTask.java:264)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at com.google.firebase.firestore.util.AsyncQueue$SynchronizedShutdownAwareExecutor$DelayedStartFactory.run(AsyncQueue.java:235)
       at java.lang.Thread.run(Thread.java:1012)
        
```

### LINKED ISSUE #2856: [Code health] Stop logging "Permission denied" when loading pass list as error
This is an expected state, so should trigger error log

### PR DESCRIPTION
**Pull request by gino-m**
Fixes #2850
Fixes #2851
Fixes #2849
Fixes #2853
Fixes #2856

### CODE REVIEW

File: ground/src/main/java/com/google/android/ground/persistence/local/room/stores/RoomSubmissionStore.kt [hunk 1]
```diff
@@ -226,13 +226,13 @@ class RoomSubmissionStore @Inject internal constructor() : LocalSubmissionStore
       .map { mutations ->
         mutations.filter { it.surveyId == survey.id }.map { it.toModelObject(survey) }
       }
-      .catch { Timber.e("Ignoring invalid submission mutation", it) }
+      .catch { Timber.e("Ignoring invalid submission mutation $it") }
```
Comment (shobhitagarwal1612) [inline ground/src/main/java/com/google/android/ground/persistence/local/room/stores/RoomSubmissionStore.kt:229]: We should change the order of throwable to Timber.e(it, "msg")


Timber.e(throwable, "error message", extra msg args)

File: ground/src/main/java/com/google/android/ground/persistence/local/room/stores/RoomSubmissionStore.kt [hunk 2]
```diff
@@ -226,13 +226,13 @@ class RoomSubmissionStore @Inject internal constructor() : LocalSubmissionStore
...
 
   override fun getAllMutationsFlow(): Flow<List<SubmissionMutation>> =
     submissionMutationDao
       .getAllMutationsFlow()
       .map { it.mapNotNull { mutation -> convertMutation(mutation) } }
-      .catch { Timber.e("ignoring invalid submission mutation", it) }
+      .catch { Timber.e("ignoring invalid submission mutation $it") }
```
Comment (shobhitagarwal1612) [inline ground/src/main/java/com/google/android/ground/persistence/local/room/stores/RoomSubmissionStore.kt:235]: Same as above

File: ground/src/main/java/com/google/android/ground/persistence/sync/LocalMutationSyncWorker.kt [hunk 3]
```diff
@@ -120,19 +121,17 @@ constructor(
     } catch (t: Throwable) {
       // Mark all mutations as having failed since the remote datastore only commits when all
       // mutations have succeeded.
-      Timber.d(t, "Local mutation sync failed")
       mutationRepository.markAsFailed(mutations, t)
-      val crashlytics = FirebaseCrashLogger()
-      crashlytics.setSelectedSurveyId(mutations.first().surveyId)
-      crashlytics.logException(t)
+      firebaseCrashLogger.setSelectedSurveyId(mutations.first().surveyId)
```
Comment (shobhitagarwal1612) [inline ground/src/main/java/com/google/android/ground/persistence/sync/LocalMutationSyncWorker.kt:125]: Instead of setting it survey id as "selectedSurveyId" which is misleading in this case, can we log it in the error message?

**Review by shobhitagarwal1612 — CHANGES_REQUESTED** [review]

File: ground/src/main/java/com/google/android/ground/persistence/local/room/stores/RoomSubmissionStore.kt (hunk 1 above)
Comment (gino-m) [reply ground/src/main/java/com/google/android/ground/persistence/local/room/stores/RoomSubmissionStore.kt:229]: Ah, sorry, I missed that this is actually the exception.

File: ground/src/main/java/com/google/android/ground/persistence/sync/LocalMutationSyncWorker.kt (hunk 3 above)
Comment (gino-m) [reply ground/src/main/java/com/google/android/ground/persistence/sync/LocalMutationSyncWorker.kt:125]: Good catch.

File: ground/src/main/java/com/google/android/ground/persistence/sync/MediaUploadWorker.kt [hunk 4]
```diff
@@ -129,19 +128,17 @@ constructor(
     val path = photoTaskData.remoteFilename
     val photoFile = userMediaRepository.getLocalFileFromRemotePath(path)
     if (!photoFile.exists()) {
-      Timber.e("Photo not found. local path: ${photoFile.path}, remote path: $path")
-      return kotlin.Result.failure(
-        FileNotFoundException("Photo $path not found on device: ${photoFile.path}")
-      )
+      val e = FileNotFoundException("Photo $path not found on device: ${photoFile.path}")
+      Timber.e("Photo not found at ${photoFile.path}")
```
[the remark this answers is not in the document]
Comment (gino-m) [reply ground/src/main/java/com/google/android/ground/persistence/sync/MediaUploadWorker.kt:132]: Tried to clean this up a big, lmkwyt. Note that the calling logic is still incorrect https://github.com/google/ground-android/issues/2120

File: ground/src/main/java/com/google/android/ground/persistence/sync/SurveySyncWorker.kt [hunk 5]
```diff
@@ -53,16 +53,9 @@ constructor(
...
-      logger.setSelectedSurveyId(surveyId)
-      logger.logException(t)
-      return if (this.runAttemptCount > MAX_SYNC_WORKER_RETRY_ATTEMPTS) {
-        Timber.v(t, "Survey sync failed too many times. Giving up.")
-        Result.failure()
-      } else {
-        Timber.v(t, "Survey sync. Retrying...")
-        Result.retry()
-      }
+      firebaseCrashLogger.setSelectedSurveyId(surveyId)
```
[the remark this answers is not in the document]
Comment (gino-m) [reply ground/src/main/java/com/google/android/ground/persistence/sync/SurveySyncWorker.kt:56]: Done!

**Comment by gino-m** [comment]
@shobhitagarwal1612 RFAL!

File: ground/src/main/java/com/google/android/ground/persistence/sync/MediaUploadWorker.kt [hunk 6]
```diff
@@ -125,26 +125,23 @@ constructor(
...
+      val path = photoTaskData.remoteFilename
+      val photoFile = userMediaRepository.getLocalFileFromRemotePath(path)
+      Timber.d("Starting photo upload. local path: ${photoFile.path}, remote path: $path")
+      if (!photoFile.exists()) {
+        throw FileNotFoundException(photoFile.path)
+      }
       remoteStorageManager.uploadMediaFromFile(photoFile, path)
       kotlin.Result.success(Unit)
+    } catch (t: FirebaseException) {
+      Timber.d(t, "Can't connect to Firebase to upload photo")
```
Comment (shobhitagarwal1612) [inline ground/src/main/java/com/google/android/ground/persistence/sync/MediaUploadWorker.kt:139]: Can we change the log level to `Timber.e`, since it could be any exception (and not just connectivity issue)?

File: ground/src/main/java/com/google/android/ground/persistence/sync/SurveySyncWorker.kt [hunk 7]
```diff
@@ -20,9 +20,10 @@ import android.content.Context
 import androidx.hilt.work.HiltWorker
 import androidx.work.CoroutineWorker
 import androidx.work.Data
+import androidx.work.ListenableWorker.Result.failure
+import androidx.work.ListenableWorker.Result.retry
+import androidx.work.ListenableWorker.Result.success
 import androidx.work.WorkerParameters
-import com.google.android.ground.Config.MAX_SYNC_WORKER_RETRY_ATTEMPTS
```
Comment (shobhitagarwal1612) [inline ground/src/main/java/com/google/android/ground/persistence/sync/SurveySyncWorker.kt:24]: Can we cleanup this var from `Config.kt`?

File: ground/src/main/java/com/google/android/ground/ui/tos/TermsOfServiceViewModel.kt [hunk 8]
```diff
@@ -56,16 +56,10 @@ constructor(
...
-          onGetTosFailure()
-        }
-        else -> {
-          Timber.e("Unexpected error: ${e.message}")
-          onGetTosFailure()
-        }
+      if (e !is TimeoutCancellationException && !e.isPermissionDeniedException()) {
+        Timber.e(e, "Failed to load Terms of Service")
       }
+      onGetTosFailure()
```
Comment (shobhitagarwal1612) [inline ground/src/main/java/com/google/android/ground/ui/tos/TermsOfServiceViewModel.kt:62]: The error handling shows a generic message "Could not connect, try again later" for all kinds of exceptions. Can we file a bug or a TODO to handle this more elegantly?

**Review by shobhitagarwal1612 — CHANGES_REQUESTED** [review]

File: ground/src/main/java/com/google/android/ground/ui/tos/TermsOfServiceViewModel.kt (hunk 8 above)
Comment (gino-m) [reply ground/src/main/java/com/google/android/ground/ui/tos/TermsOfServiceViewModel.kt:62]: Filed https://github.com/google/ground-android/issues/2858 to track!

File: ground/src/main/java/com/google/android/ground/persistence/sync/SurveySyncWorker.kt (hunk 7 above)
Comment (gino-m) [reply ground/src/main/java/com/google/android/ground/persistence/sync/SurveySyncWorker.kt:24]: Done!

File: ground/src/main/java/com/google/android/ground/persistence/sync/MediaUploadWorker.kt (hunk 6 above)
Comment (gino-m) [reply ground/src/main/java/com/google/android/ground/persistence/sync/MediaUploadWorker.kt:139]: Crashlytics logs were noisy due to users being offline. How about I update this to only log the more specific `FirebaseNetworkException` as debug, all others as error?

File: ground/src/main/java/com/google/android/ground/ui/tos/TermsOfServiceViewModel.kt [hunk 9]
```diff
@@ -56,13 +56,16 @@ constructor(
         }
       emit(Html.fromHtml(html, 0))
     } catch (e: Throwable) {
-      if (e !is TimeoutCancellationException && !e.isPermissionDeniedException()) {
+      if (e.isExpectedFailure()) {
```
Comment (shobhitagarwal1612) [inline ground/src/main/java/com/google/android/ground/ui/tos/TermsOfServiceViewModel.kt:59]: Don't we have to negate the condition?

**Review by shobhitagarwal1612 — CHANGES_REQUESTED** [review]

File: ground/src/main/java/com/google/android/ground/ui/tos/TermsOfServiceViewModel.kt (hunk 9 above)
Comment (gino-m) [reply ground/src/main/java/com/google/android/ground/ui/tos/TermsOfServiceViewModel.kt:59]: Ugh, you're right. Thanks for catching this!

**Review by shobhitagarwal1612 — APPROVED** [review]
