### PR TITLE
Switch to main thread when updating submission count

### LINKED ISSUE #2015: Force quit on "Collect data"
This occurred when running in emulator, not sure of other repro steps:

```
FATAL EXCEPTION: DefaultDispatcher-worker-7
                 Process: com.google.android.ground, PID: 26165
                 android.view.ViewRootImpl$CalledFromWrongThreadException: Only the original thread that created a view hierarchy can touch its views.
                 	at android.view.ViewRootImpl.checkThread(ViewRootImpl.java:8191)
                 	at android.view.ViewRootImpl.requestLayout(ViewRootImpl.java:1420)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at androidx.drawerlayout.widget.DrawerLayout.requestLayout(DrawerLayout.java:1353)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at androidx.constraintlayout.widget.ConstraintLayout.requestLayout(ConstraintLayout.java:3605)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at androidx.recyclerview.widget.RecyclerView.requestLayout(RecyclerView.java:4412)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at androidx.constraintlayout.widget.ConstraintLayout.requestLayout(ConstraintLayout.java:3605)
                 	at android.view.View.requestLayout(View.java:24454)
                 	at android.widget.TextView.checkForRelayout(TextView.java:9681)
                 	at android.widget.TextView.setText(TextView.java:6269)
                 	at android.widget.TextView.setText(TextView.java:6097)
                 	at android.widget.TextView.setText(TextView.java:6049)
                 	at com.google.android.ground.ui.home.mapcontainer.cards.MapCardAdapter$LoiViewHolder$bind$1$1.invokeSuspend(MapCardAdapter.kt:157)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
                 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
                 	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@d20eaf1, Dispatchers.Default]
```

@shobhitagarwal1612 Are we using the ViewHolder correctly in `MapCardAdapter`?

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Fixes #2015

@gino-m  PTAL?

### CODE REVIEW

File: ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/cards/MapCardAdapter.kt [hunk 1]
```diff
@@ -154,7 +156,9 @@ class MapCardAdapter(
 
         coroutineScope.launch {
           val submissionCount = fetchSubmissionCount(loi)
-          submissions.text = LoiCardUtil.getSubmissionsText(submissionCount)
+          withContext(Dispatchers.Main) {
+            submissions.text = LoiCardUtil.getSubmissionsText(submissionCount)
```
Comment (gino-m) [inline ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/cards/MapCardAdapter.kt:160]: See https://github.com/google/ground-android/issues/2015#issuecomment-1785804529

**Review by gino-m — CHANGES_REQUESTED** [review]

File: ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/cards/MapCardAdapter.kt (hunk 1 above)
Comment (shobhitagarwal1612) [reply ground/src/main/java/com/google/android/ground/ui/home/mapcontainer/cards/MapCardAdapter.kt:160]: Replied in the same bug.

**Review by gino-m — APPROVED** [review]
Thanks!
