### PR TITLE
[PhotoTaskFragment] Remove decodeBitmap approach

### LINKED ISSUE #3102: Photo-taking task crashes app
eMail from user:

_"Picture taking form field in campaign A makes the app crash every time we try to take a picture, so we are just skipping it for the time being. It works in survey B though, which makes me think that it is the picture taking form field, in combination with some other data field(s), that the app is not tolerating."_

I can confirm that collecting for another survey in my app (picture taking required & can't be skipped) does not work, instead a "Unsaved data restored" pop-up appears. Survey: https://ground.openforis.org/survey/N5hZgxQ8MnKDD8lhDwMs Build 0.1.17

Same does not work reproduced in a survey where the picture-taking can be skipped.
Skipping and getting to the last page ("Data collected successfully") the app fully crashes.

### PR DESCRIPTION
**Pull request by anandwana001**
Fixes #3102 

@shobhitagarwal1612 @rfontanarosa  PTAL?

### CODE REVIEW

File: app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/photo/PhotoTaskFragment.kt [hunk 1]
```diff
@@ -62,25 +62,30 @@ class PhotoTaskFragment : AbstractTaskFragment<PhotoTaskViewModel>() {
...
   private var taskWaitingForPhoto: String? = null
   private var capturedPhotoPath: String? = null
   private lateinit var capturedPhotoUri: Uri
 
+  override fun onCreate(savedInstanceState: Bundle?) {
+    super.onCreate(savedInstanceState)
+    capturePhotoLauncher =
+      registerForActivityResult(ActivityResultContracts.TakePicture()) { result: Boolean ->
+        externalScope.launch(Dispatchers.IO) {
+          if (result) {
```
Comment (gino-m) [inline app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/photo/PhotoTaskFragment.kt]: `if (!result) return`

**Review by gino-m — APPROVED** [review]
Lgtm, one nit.

File: app/src/main/java/org/groundplatform/android/repository/UserMediaRepository.kt [hunk 2]
```diff
@@ -74,16 +77,46 @@ constructor(
    * memory, preserving the original quality, metadata, and resolution. It avoids potential
    * OutOfMemoryError caused by loading large images into a Bitmap.
    */
-  @Throws(IOException::class)
-  suspend fun savePhotoFromUri(uri: Uri, fieldId: String): File {
-    val file = createImageFile(fieldId)
+  suspend fun savePhotoFromUri(uri: Uri, fieldId: String): File =
+    withContext(Dispatchers.IO) {
+      val file = createImageFile(fieldId)
```
Comment (gino-m) [inline app/src/main/java/org/groundplatform/android/repository/UserMediaRepository.kt:81]: `UserMediaRepository` shouldn't know about the `fieldId` - in the future we should abstract this away from this class

File: app/src/main/java/org/groundplatform/android/repository/UserMediaRepository.kt [hunk 3]
```diff
@@ -74,16 +77,46 @@ constructor(
...
 
-    context.contentResolver.openInputStream(uri)?.use { input ->
-      FileOutputStream(file).use { output -> input.copyTo(output) }
-    } ?: throw IOException("Unable to open URI: $uri")
+      val bitmap = decodeSampledBitmapFromUri(uri)
+      FileOutputStream(file).use { output ->
+        bitmap.compress(Bitmap.CompressFormat.JPEG, 85, output)
```
Comment (gino-m) [inline app/src/main/java/org/groundplatform/android/repository/UserMediaRepository.kt]: Why do we need to recompress the image? Isn't it written as JPEG to the location specified in `MediaStore.EXTRA_OUTPUT` when the photo Intent is triggered?

File: app/src/main/java/org/groundplatform/android/repository/UserMediaRepository.kt [hunk 4]
```diff
@@ -74,16 +77,46 @@ constructor(
...
+      }
 
-    Timber.d("Photo saved %s : %b", file.path, file.exists())
-    return file
+      Timber.d("Photo saved %s : %b", file.path, file.exists())
```
Comment (gino-m) [inline app/src/main/java/org/groundplatform/android/repository/UserMediaRepository.kt]: You can use template strings in Kotlin for better readability.

File: app/src/main/java/org/groundplatform/android/repository/UserMediaRepository.kt (hunk 3 above)
Comment (anandwana001) [reply app/src/main/java/org/groundplatform/android/repository/UserMediaRepository.kt]: we are not using `MediaStore.EXTRA_OUTPUT` anywhere, unable to find it.
@shobhitagarwal1612 anything on this do you know?

File: app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/photo/PhotoTaskFragment.kt [hunk 5]
```diff
@@ -135,6 +132,23 @@ class PhotoTaskFragment : AbstractTaskFragment<PhotoTaskViewModel>() {
     outState.putString(CAPTURED_PHOTO_PATH, capturedPhotoPath)
   }
 
+  private fun handleCaptureResult(result: Boolean) {
+    if (!result || viewModel.capturedUri == null) {
```
Comment (gino-m) [inline app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/photo/PhotoTaskFragment.kt:137]: Move null check into launch block

File: app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/photo/PhotoTaskViewModel.kt [hunk 6]
```diff
@@ -58,18 +65,21 @@ constructor(
...
-      val bitmap = bitmapUtil.fromUri(uri)
-      val file = userMediaRepository.savePhoto(bitmap, currentTask)
-      userMediaRepository.addImageToGallery(file.absolutePath, file.name)
-      val remoteFilename = FirebaseStorageManager.getRemoteMediaPath(surveyId, file.name)
-      setValue(PhotoTaskData(remoteFilename))
-    } catch (e: IOException) {
-      Timber.e(e, "Error getting photo selected from storage")
+        withContext(Dispatchers.Main) { setValue(PhotoTaskData(remoteFilename)) }
+      } catch (e: IOException) {
+        Timber.e(e, "Error getting photo selected from storage")
```
Comment (gino-m) [inline app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/photo/PhotoTaskViewModel.kt]: We need to let user know if saving photo fails, perhaps with toast

File: app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/photo/PhotoTaskViewModel.kt [hunk 7]
```diff
@@ -58,18 +65,21 @@ constructor(
...
+      } catch (e: Exception) {
```
Comment (gino-m) [inline app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/photo/PhotoTaskViewModel.kt]: Don't need to cancel all Exception imo

**Review by gino-m — CHANGES_REQUESTED** [review]
Please fix PR title

File: app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/photo/PhotoTaskFragment.kt [hunk 8]
```diff
@@ -135,6 +132,23 @@ class PhotoTaskFragment : AbstractTaskFragment<PhotoTaskViewModel>() {
...
+      Timber.e("Photo capture failed or URI not set")
+      return
+    }
+
+    externalScope.launch(Dispatchers.IO) {
```
Comment (gino-m) [inline app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/photo/PhotoTaskFragment.kt]: Does this while thing need to happen on IO thread, or just `savePhotoTaskData`?

File: app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/photo/PhotoTaskViewModel.kt [hunk 9]
```diff
@@ -58,18 +65,21 @@ constructor(
    * Saves photo data stored on an on-device URI in Ground-associated storage and prepares it for
    * inclusion in a data collection submission.
    */
-  suspend fun savePhotoTaskData(uri: Uri) {
+  fun savePhotoTaskData(uri: Uri) {
     val currentTask = taskWaitingForPhoto
     requireNotNull(currentTask) { "Photo captured but no task waiting for the result" }
+    externalScope.launch(Dispatchers.IO) {
```
Comment (gino-m) [inline app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/photo/PhotoTaskViewModel.kt]: We spoke, @shobhitagarwal1612 and I agree it would be clearer if the caller switched to IO thread instead of this fun.

**Review by gino-m — DISMISSED** [review]

File: app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/photo/PhotoTaskFragment.kt [hunk 10]
```diff
@@ -61,25 +61,22 @@ class PhotoTaskFragment : AbstractTaskFragment<PhotoTaskViewModel>() {
...
   private var taskWaitingForPhoto: String? = null
   private var capturedPhotoPath: String? = null
   private lateinit var capturedPhotoUri: Uri
 
+  override fun onCreate(savedInstanceState: Bundle?) {
+    super.onCreate(savedInstanceState)
+
+    capturePhotoLauncher =
+      registerForActivityResult(ActivityResultContracts.TakePicture()) { result: Boolean ->
+        externalScope.launch(Dispatchers.IO) { handleCaptureResult(result) }
```
Comment (shobhitagarwal1612) [inline app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/photo/PhotoTaskFragment.kt]: Can we inject `IoDispatcher` instead of using `Dispatchers.IO`? This would allow testing the feature using test dispatchers in unit tests.

File: app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/photo/PhotoTaskViewModel.kt [hunk 11]
```diff
@@ -63,13 +63,13 @@ constructor(
...
 
     try {
-      val bitmap = bitmapUtil.fromUri(uri)
-      val file = userMediaRepository.savePhoto(bitmap, currentTask)
+      val file = userMediaRepository.savePhotoFromUri(uri, currentTask)
       userMediaRepository.addImageToGallery(file.absolutePath, file.name)
       val remoteFilename = FirebaseStorageManager.getRemoteMediaPath(surveyId, file.name)
-      setValue(PhotoTaskData(remoteFilename))
+
+      withContext(Dispatchers.Main) { setValue(PhotoTaskData(remoteFilename)) }
```
Comment (shobhitagarwal1612) [inline app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/photo/PhotoTaskViewModel.kt:70]: As discussed, we can directly update the value from background thread using `postValue` without having to change the thread.

File: app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/photo/PhotoTaskFragment.kt [hunk 12]
```diff
@@ -97,21 +94,20 @@ class PhotoTaskFragment : AbstractTaskFragment<PhotoTaskViewModel>() {
...
-    }
   }
 
   override fun onTaskViewAttached() {
     viewModel.surveyId = dataCollectionViewModel.surveyId
     viewModel.taskWaitingForPhoto = taskWaitingForPhoto
+
+    viewModel.capturedUri?.let { uri ->
+      if (!viewModel.hasLaunchedCamera) {
+        externalScope.launch {
```
Comment (shobhitagarwal1612) [inline app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/photo/PhotoTaskFragment.kt]: Should this be using ioDispatcher too?

File: app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/photo/PhotoTaskViewModel.kt (hunk 11 above)
Comment (anandwana001) [reply app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/photo/PhotoTaskViewModel.kt:70]: this setValue is not the LiveData, it is a part of AbstractTaskViewModel.
