### PR TITLE
[Feature disambiguation dialog] Fix crash on device rotate

### LINKED ISSUE #858: [Feature disambiguation dialog] Rotating device while dialog is showing crashes app
```
2021-06-05 17:58:06.338 11879-11879/com.google.android.gnd E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.google.android.gnd, PID: 11879
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.google.android.gnd/com.google.android.gnd.MainActivity}: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.google.android.gnd.ui.home.featureselector.FeatureSelectorFragment: could not find Fragment constructor
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2913)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048)
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:4784)
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4693)
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment com.google.android.gnd.ui.home.featureselector.FeatureSelectorFragment: could not find Fragment constructor
        at androidx.fragment.app.Fragment.instantiate(Fragment.java:563)
        at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
        at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:390)
        at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:74)
        at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2454)
        at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1706)
        at androidx.fragment.app.Fragment.onCreate(Fragment.java:1683)
        at androidx.navigation.fragment.NavHostFragment.onCreate(NavHostFragment.java:264)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2684)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1175)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356)
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497)
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625)
        at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2571)
        at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:236)
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:315)
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115)
        at com.google.android.gnd.AbstractActivity.onCreate(AbstractActivity.java:47)
        at com.google.android.gnd.Hilt_MainActivity.onCreate(Hilt_MainActivity.java:28)
        at com.google.android.gnd.MainActivity.onCreate(MainActivity.java:64)
        at android.app.Activity.performCreate(Activity.java:7136)
        at android.app.Activity.performCreate(Activity.java:7127)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:4784) 
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4693) 
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
     Caused by: java.lang.NoSuchMethodException: <init> []
        at java.lang.Class.getConstructor0(Class.java:2327)
        at java.lang.Class.getConstructor(Class.java:1725)
        at androidx.fragment.app.Fragment.instantiate(Fragment.java:548)
        at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57) 
        at androidx.fragment.app.FragmentManager$3.instantiate(FragmentManager.java:390) 
        at androidx.fragment.app.FragmentStateManager.<init>(FragmentStateManager.java:74) 
        at androidx.fragment.app.FragmentManager.restoreSaveState(FragmentManager.java:2454) 
        at androidx.fragment.app.Fragment.restoreChildFragmentState(Fragment.java:1706) 
        at androidx.fragment.app.Fragment.onCreate(Fragment.java:1683) 
        at androidx.navigation.fragment.NavHostFragment.onCreate(NavHostFragment.java:264) 
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2684) 
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280) 
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1175) 
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1356) 
        at androidx.fragment.app.FragmentManager.moveFragmentToExpectedState(FragmentManager.java:1434) 
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1497) 
        at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:2625) 
        at androidx.fragment.app.FragmentManager.dispatchCreate(FragmentManager.java:2571) 
        at androidx.fragment.app.FragmentController.dispatchCreate(FragmentController.java:236) 
        at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:315) 
        at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:115) 
        at com.google.android.gnd.AbstractActivity.onCreate(AbstractActivity.java:47) 
        at com.google.android.gnd.Hilt_MainActivity.onCreate(Hilt_MainActivity.java:28) 
        at com.google.android.gnd.MainActivity.onCreate(MainActivity.java:64) 
        at android.app.Activity.performCreate(Activity.java:7136) 
        at android.app.Activity.performCreate(Activity.java:7127) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2893) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3048) 
        at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:4784) 
        at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4693) 
        at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6669) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858) 
```

@scolsen FYI

### PR DESCRIPTION
**Pull request by gino-m**
Also includes a few small refactors.

Fixes #858

@scolsen PTAL?

### CODE REVIEW

File: gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java [hunk 1]
```diff
@@ -278,7 +273,7 @@ public void showSettings() {
   }
 
   public Observable<ImmutableList<Feature>> getOverlappingFeaturesOnceAndStream() {
-    return overlappingFeaturesSubject;
+    return showFeatureSelectorRequests;
```
Comment (scolsen) [inline gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java:276]: This now duplicates lines 149-151. We should probably remove `getOverlappingFeaturesOnceAndStream`

File: gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java [hunk 2]
```diff
@@ -287,7 +282,18 @@ public void onFeatureClick(ImmutableList<MapFeature> mapFeatures) {
...
             .filter(f -> f != null)
             .collect(toImmutableList());
-    overlappingFeaturesSubject.onNext(features);
+
+    if (features.isEmpty()) {
+      Timber.e("onFeatureClick called with empty or null map features");
+      return;
+    }
+
+    if (features.size() == 1) {
```
Comment (scolsen) [inline gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java:291]: optional: Splitting hairs, but imo deciding when to show the bottom sheet is something that should be handled in the view not the view model, since we're making UI decisions. Maybe we can drop the bottom sheet behavior from the VM entirely, and restrict the VM to managing data (which is not too much in this case).

**Review by scolsen — CHANGES_REQUESTED** [review]
Some small comments but otherwise looks good!

File: gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java (hunk 2 above)
Comment (gino-m) [reply gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java:288]: In Jetpack I believe the recommendation is the keep as much logic as possible out of view, mostly because they're hard to unit test. In my understanding, views are really just for plumbing; the lowest UI layer close to Android SDK and OS. If this is a decision point the view needs to make, I believe it's correct to model in the in view model (thusly named).

File: gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java (hunk 1 above)
Comment (gino-m) [reply gnd/src/main/java/com/google/android/gnd/ui/home/HomeScreenViewModel.java]: Done!

**Comment by gino-m** [comment]
/gcbrun

@scolsen PTAL?
