### PR TITLE
Fix bug in capture location task

### LINKED ISSUE #1986: Capture location flow broken
- [ ] Doesn't force on location lock
- [ ] Clicking "Capture" has no effect

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Fixes #1986

@gino-m  PTAL?

### CODE REVIEW

File: ground/src/main/java/com/google/android/ground/ui/common/BaseMapViewModel.kt [hunk 1]
```diff
@@ -219,6 +222,9 @@ constructor(
       .collect { (index, coordinates) ->
         if (index == 0) {
           panAndZoomCamera(coordinates)
+          // Set a small delay before emitting another value to allow previous zoom animation to
+          // finish. Otherwise, the map camera stops at some other zoom level.
+          delay(3000)
```
Comment (gino-m) [inline ground/src/main/java/com/google/android/ground/ui/common/BaseMapViewModel.kt:227]: I think the root problem is that we don't have a clear source of truth of the map state at the moment. In most cases, we're relying on the GoogleMap to tell us its current state, in others it's in the adapter, and yet others in the VM base class or concrete subclass. Ideally we would track the zoom level in a VM associated with the MapFragment and use it in `panCamera()`. Would you be able to add a `TODO(#1889)` for this?

**Review by gino-m — CHANGES_REQUESTED** [review]

File: ground/src/main/java/com/google/android/ground/ui/common/BaseMapViewModel.kt (hunk 1 above)
Comment (shobhitagarwal1612) [reply ground/src/main/java/com/google/android/ground/ui/common/BaseMapViewModel.kt:230]: Done

**Review by gino-m — APPROVED** [review]
Thanks!
