### PR TITLE
Drop and Data Fragment test fix

### LINKED ISSUE #3371: [Code health] Unit Test Failing for Drop and Data Fragment

### PR DESCRIPTION
**Pull request by anandwana001**
Fixes #3371 

@shobhitagarwal1612  PTAL?

### CODE REVIEW

File: app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/AbstractTaskFragment.kt [hunk 1]
```diff
@@ -236,17 +236,27 @@ abstract class AbstractTaskFragment<T : AbstractTaskViewModel> : AbstractFragmen
...
   }
 
+  @Composable
+  private fun ActionButtonsRow() {
+    Row(modifier = Modifier.fillMaxWidth(), horizontalArrangement = Arrangement.SpaceBetween) {
+      buttonDataList.sortedBy { it.index }.forEach { (_, button) -> button.CreateButton() }
+    }
+  }
+
+  open fun shouldShowHeader() = false
```
Comment (shobhitagarwal1612) [inline app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/AbstractTaskFragment.kt:259]: Please add ktdoc

**Review by shobhitagarwal1612 — APPROVED** [review]
