### PR TITLE
Fixing the Core issue for the Photo Crash

### LINKED ISSUE #3193: [Picasso] Replace Picasso with Android Image Loading

### PR DESCRIPTION
**Pull request by anandwana001**
Fixes #3193 

The core reason of the photo crash is due to onResume hit.

Each time a user capture the image, onResume callback hit in the MainActivity which restarts the navigation execution and due to collecting the only first emission, it never jumps to photo fragment and due to which it was jumping to home screen in the loop.

We have to make a new flow of checking auth status each time we resume the app.

https://github.com/user-attachments/assets/331c3906-f77d-4445-bcb3-20ff9c4ae5cb

@shobhitagarwal1612  PTAL?

### CODE REVIEW

File: app/src/main/java/org/groundplatform/android/persistence/local/room/LocalDatabase.kt [hunk 1]
```diff
@@ -90,7 +90,12 @@ import org.groundplatform.android.persistence.local.room.fields.TileSetEntitySta
     ],
   version = Config.DB_VERSION,
   exportSchema = true,
-  autoMigrations = [AutoMigration(from = 120, to = 121), AutoMigration(from = 121, to = 122)],
+  autoMigrations =
```
Comment (shobhitagarwal1612) [inline app/src/main/java/org/groundplatform/android/persistence/local/room/LocalDatabase.kt]: Should this be moved to a separate PR?

File: app/schemas/org.groundplatform.android.persistence.local.room.LocalDatabase/122.json [hunk 2]
```diff
@@ -617,7 +617,7 @@
       },
       {
         "tableName": "survey",
-        "createSql": "CREATE TABLE IF NOT EXISTS `${TABLE_NAME}` (`id` TEXT NOT NULL, `title` TEXT, `description` TEXT, `acl` TEXT, `data_sharing_terms` BLOB, PRIMARY KEY(`id`))",
+        "createSql": "CREATE TABLE IF NOT EXISTS `${TABLE_NAME}` (`id` TEXT NOT NULL, `title` TEXT, `description` TEXT, `acl` TEXT, `data_sharing_terms` BLOB, `general_access` INTEGER, PRIMARY KEY(`id`))",
```
Comment (shobhitagarwal1612) [inline app/schemas/org.groundplatform.android.persistence.local.room.LocalDatabase/122.json]: Why is this required?

**Comment by anandwana001** [comment]
https://github.com/google/ground-android/issues/3182

**Comment by gino-m** [comment]
@anandwana001 Please describe the issue more clearly and we can merge.

File: app/src/main/java/org/groundplatform/android/ui/common/BindingAdapters.kt [hunk 3]
```diff
@@ -52,14 +55,25 @@ object BindingAdapters {
...
-        .load(uri)
-        .placeholder(R.drawable.ic_photo_grey_600_24dp)
-        .transform(RotateUsingExif(uri, view.context))
-        .into(view)
-    } catch (exception: IllegalStateException) {
-      // Needed for running unit tests
-      Timber.e(exception)
+      val context = view.context
+
+      val bitmap =
```
Comment (gino-m) [inline app/src/main/java/org/groundplatform/android/ui/common/BindingAdapters.kt]: @anandwana001 Is this necessary?

**Review by gino-m — CHANGES_REQUESTED** [review]

File: app/src/main/java/org/groundplatform/android/ui/common/BindingAdapters.kt (hunk 3 above)
Comment (anandwana001) [reply app/src/main/java/org/groundplatform/android/ui/common/BindingAdapters.kt]: yes, for EXIF rotation. we need this.

Comment (gino-m) [reply app/src/main/java/org/groundplatform/android/ui/common/BindingAdapters.kt]: Then we should use https://developer.android.com/reference/android/media/ExifInterface to load the header without loading the whole file.

Comment (anandwana001) [reply app/src/main/java/org/groundplatform/android/ui/common/BindingAdapters.kt]: done

File: app/src/main/java/org/groundplatform/android/ui/common/BindingAdapters.kt [hunk 4]
```diff
@@ -52,14 +52,11 @@ object BindingAdapters {
     if (view == null || uri == null) return
 
     try {
-      Picasso.get()
```
Comment (shobhitagarwal1612) [inline app/src/main/java/org/groundplatform/android/ui/common/BindingAdapters.kt:55]: Can we cleanup the gradle dependency too?

File: app/src/main/java/org/groundplatform/android/ui/common/BindingAdapters.kt [hunk 5]
```diff
@@ -52,14 +52,11 @@ object BindingAdapters {
...
-        .load(uri)
-        .placeholder(R.drawable.ic_photo_grey_600_24dp)
```
Comment (shobhitagarwal1612) [inline app/src/main/java/org/groundplatform/android/ui/common/BindingAdapters.kt:57]: Is it possible to preserve the placeholder logic?

File: app/src/main/java/org/groundplatform/android/ui/common/BindingAdapters.kt [hunk 6]
```diff
@@ -52,14 +52,11 @@ object BindingAdapters {
...
-        .transform(RotateUsingExif(uri, view.context))
-        .into(view)
-    } catch (exception: IllegalStateException) {
-      // Needed for running unit tests
-      Timber.e(exception)
+      val rotatedBitmap = loadBitmapWithCorrectOrientation(view.context, uri)
+      view.setImageBitmap(rotatedBitmap)
+    } catch (e: Exception) {
```
Comment (shobhitagarwal1612) [inline app/src/main/java/org/groundplatform/android/ui/common/BindingAdapters.kt]: It's generally not advisable to use a generic "catch-all" for exceptions. A more robust approach is to explicitly list and handle the specific exceptions you expect to occur. In cases where no particular exceptions are foreseen, it's often better to allow the program to fail gracefully rather than attempting to catch an unknown error.

File: app/src/main/java/org/groundplatform/android/ui/util/RotateUsingExif.kt [hunk 7]
```diff
@@ -17,60 +17,51 @@ package org.groundplatform.android.ui.util
...
     }
-
-  /** Returns the EXIF orientation attribute of the JPEG image at the specified URI. */
-  private fun getOrientationFromExif(uri: Uri): Int {
-    val inputStream =
-      context.contentResolver.openInputStream(uri)
-        ?: throw IOException("Content resolver returned null for $uri")
-    val exif = ExifInterface(inputStream)
-    return exif.getAttributeInt(ExifInterface.TAG_ORIENTATION, ExifInterface.ORIENTATION_NORMAL)
   }
```
Comment (shobhitagarwal1612) [inline app/src/main/java/org/groundplatform/android/ui/util/RotateUsingExif.kt]: Can we preserve the existing methods `getRotationDegrees` and `getOrientationFromExif`? These lines haven't changed and would help reduce the diff count in the PR

File: app/src/main/java/org/groundplatform/android/ui/common/BindingAdapters.kt (hunk 4 above)
Comment (anandwana001) [reply app/src/main/java/org/groundplatform/android/ui/common/BindingAdapters.kt:55]: other places are still using it

Comment (anandwana001) [reply app/src/main/java/org/groundplatform/android/ui/common/BindingAdapters.kt:55]: https://github.com/google/ground-android/issues/3193

File: app/src/main/java/org/groundplatform/android/ui/common/BindingAdapters.kt (hunk 5 above)
Comment (anandwana001) [reply app/src/main/java/org/groundplatform/android/ui/common/BindingAdapters.kt:57]: not directly, but one approach is to set the placeholder meanwhile the bitmap is coming.

Comment (anandwana001) [reply app/src/main/java/org/groundplatform/android/ui/common/BindingAdapters.kt:57]: done

File: app/src/main/java/org/groundplatform/android/ui/common/BindingAdapters.kt (hunk 4 above)
Comment (shobhitagarwal1612) [reply app/src/main/java/org/groundplatform/android/ui/common/BindingAdapters.kt:55]: Are there any other usages of Picasso left? Can we do it in the same PR?

Comment (anandwana001) [reply app/src/main/java/org/groundplatform/android/ui/common/BindingAdapters.kt:55]: removed

**Review by shobhitagarwal1612 — APPROVED** [review]
LGTM! Thanks
