### PR TITLE
[UserRepository] User can submit to Public as well as Unlisted survey

### LINKED ISSUE #3157: Error collecting data for a publicly listed survey from another account
**Describe the bug**
Unable to collect data for a public survey owned by someone else

**App version**
At head

**To Reproduce**
1. User A creates a new survey and makes it public
2. User B opens the app and activates it
3. See error in logcat

**Expected behavior**
User should be able to see the "+" button

**Actual behavior**
User doesn't see anything.

### PR DESCRIPTION
**Pull request by anandwana001**
Fixes #3157

We might need migration here as well
WDYT?

@shobhitagarwal1612  PTAL?

### CODE REVIEW

File: app/src/main/java/org/groundplatform/android/repository/UserRepository.kt [hunk 1]
```diff
@@ -83,6 +83,11 @@ constructor(
    * survey. If no survey is active at the moment, then it returns false.
    */
   suspend fun canUserSubmitData(): Boolean {
+    val isPublic = surveyRepository.activeSurvey?.generalAccess
+    if (isPublic?.ordinal == 3) {
```
Comment (gino-m) [inline app/src/main/java/org/groundplatform/android/repository/UserRepository.kt]: Can we use the enum here?

Comment (gino-m) [reply app/src/main/java/org/groundplatform/android/repository/UserRepository.kt]: We should also for unlisted surveys as well.

Comment (gino-m) [reply app/src/main/java/org/groundplatform/android/repository/UserRepository.kt]: surveyRepository.activeSurvey?.generalAccess == || ==..

Comment (anandwana001) [reply app/src/main/java/org/groundplatform/android/repository/UserRepository.kt]: done

**Review by shobhitagarwal1612 — CHANGES_REQUESTED** [review]
Can we add some test coverage?
