### PR TITLE
Prevent app crash when checking for current user's permissions

### LINKED ISSUE #2014: Force quit on missing ACL
If email isn't found in survey ACLs:

```
android.view.InflateException: Binary XML file line #39 in com.google.android.ground:layout/home_screen_frag: Binary XML file line #39 in com.google.android.ground:layout/home_screen_frag: Error inflating class androidx.fragment.app.FragmentContainerView
                 Caused by: android.view.InflateException: Binary XML file line #39 in com.google.android.ground:layout/home_screen_frag: Error inflating class androidx.fragment.app.FragmentContainerView
                 Caused by: java.lang.IllegalStateException: ACL not found for email  in survey Demo survey
                 	at com.google.android.ground.model.Survey.getRole(Survey.kt:40)
                 	at com.google.android.ground.repository.UserRepository.canUserSubmitData(UserRepository.kt:70)
                 	at com.google.android.ground.ui.home.mapcontainer.HomeScreenMapContainerFragment.onCreate(HomeScreenMapContainerFragment.kt:77)
```

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Fixes #2014

Tested for regression via unit tests

@gino-m  PTAL?

### CODE REVIEW

File: ground/src/main/java/com/google/android/ground/repository/UserRepository.kt [hunk 1]
```diff
@@ -69,5 +69,10 @@ constructor(
    * survey. If no survey is active at the moment, then it returns false.
    */
   fun canUserSubmitData(): Boolean =
-    surveyRepository.activeSurvey?.getRole(currentUser.email) != Role.VIEWER
+    try {
+      surveyRepository.activeSurvey?.getRole(currentUser.email) != Role.VIEWER
+    } catch (e: IllegalStateException) {
+      Timber.e(e, "Failed to check permissions for user $currentUser")
```
Comment (gino-m) [inline ground/src/main/java/com/google/android/ground/repository/UserRepository.kt:75]: Nit: Update error text: "Error getting role for user $currentUser"

**Review by gino-m — APPROVED** [review]
