### PR TITLE
[Active project] Fix project spinner bug and streamline activation flow

### LINKED ISSUE #186: [Add record] "Project loading" spinner sometimes appears after saving record while offline
The app becomes unresponsive:
Screenshot_1568512192

### PR DESCRIPTION
**Pull request by gino-m**
- [x] Moves caching of active project from InMemoryCache to stream.
- [x] Renames `Persistable` to `Loadable` now that we've removed saved state.
- [x] Adds Rx composable helpers to `Loadable` and `Result` to wrap and unwrap values in this stream. This is especially useful when propagating error states from streams implicitly subscribed inside `flatMap` and `switchMap`, in which case Rx stream errors are not propagated, but rather break the outer stream.
- [x] Move subscriptions of project activation into initialization of view layer so that disposables are cleaned up on Android lifecycle events.

Fixes #186. Contributes to #84.

### CODE REVIEW

**Comment by gino-m** [comment]
@shobhitagarwal1612 @scolsen Some ideas and WIP in e8a02d59cc4fb027dcf020f0a587b01846822c90.

File: gnd/src/main/java/com/google/android/gnd/rx/Result.java [hunk 1]
```diff
@@ -54,4 +57,35 @@ protected Result(@Nullable T value, @Nullable Throwable error) {
...
+
+  /**
+   * Returns a {@link Flowable} that maps values emitted from the source stream as Result instances.
+   * Errors in the provided stream are handled and wrapped in a Result with ERROR state. The
+   * returned stream itself should never fail with an error.
+   *
+   * @param source the stream to be modified.
+   * @param <T> the type of value being emitted.
+   */
+  public static <T> Flowable<Result<T>> wrap(Flowable<T> source) {
```
Comment (gino-m) [inline gnd/src/main/java/com/google/android/gnd/rx/Result.java]: Would changing these to operate on `Single` instead of `Flowable` possibly make more sense semantically?

Comment (gino-m) [reply gnd/src/main/java/com/google/android/gnd/rx/Result.java]: I tried this out and it seems to be more intuitive with Single, but in the end, wrap/unwrap aren't needed for this PR so removing them. Stashing them in [this gist](https://gist.github.com/gino-m/efcfd158a4d6e4461ac17a1a064d8a7e) for use when we want to wrap potentials errors without breaking a `Flowable` or `Observable`.

Comment (shobhitagarwal1612) [reply gnd/src/main/java/com/google/android/gnd/rx/Result.java]: I don't have anything useful to add to the conversation. @scolsen ?

Comment (gino-m) [reply gnd/src/main/java/com/google/android/gnd/rx/Result.java]: There's a long thread on #84, but I think we can leave that for a separate PR since this one is already growing unwieldy (sorry for that!).

File: gnd/src/main/java/com/google/android/gnd/repository/DataRepository.java [hunk 2]
```diff
@@ -72,22 +74,65 @@ public DataRepository(
...
+    }
+    String id = projectId.get();
+
+    return syncProjectWithRemote(id)
+        .doOnSubscribe(__ -> Log.i(TAG, "Activating project " + id))
+        .onErrorResumeNext(
+            localDataStore
+                .getProjectById(id)
+                .doOnSubscribe(__ -> Log.i(TAG, "Falling back to local db"))
+                .toSingle())
```
Comment (shobhitagarwal1612) [inline gnd/src/main/java/com/google/android/gnd/repository/DataRepository.java]: This would consume all kinds of exceptions even when it's not `FirebaseFirestoreException`. Do we want that?

File: gnd/src/main/java/com/google/android/gnd/repository/DataRepository.java [hunk 3]
```diff
@@ -114,51 +159,21 @@ private Completable updateLocalFeature(RemoteDataEvent<Feature> event) {
...
-              if (throwable instanceof FirebaseFirestoreException) {
-                return localDataStore.getProjects();
-              }
-              return Single.error(throwable);
-            })
-        .map(Persistable::loaded)
-        .onErrorReturn(Persistable::error)
-        .toObservable()
-        .startWith(Persistable.loading());
+        .onErrorResumeNext(localDataStore.getProjects())
```
Comment (shobhitagarwal1612) [inline gnd/src/main/java/com/google/android/gnd/repository/DataRepository.java]: Same as above

File: gnd/src/main/java/com/google/android/gnd/rx/Result.java (hunk 1 above)
Comment (shobhitagarwal1612) [reply gnd/src/main/java/com/google/android/gnd/rx/Result.java]: Thanks! Dealing with it separately sounds ok to me

File: gnd/src/main/java/com/google/android/gnd/repository/DataRepository.java (hunk 2 above)
Comment (gino-m) [reply gnd/src/main/java/com/google/android/gnd/repository/DataRepository.java]: Good catch.. is that the only exception that would be meaningful here? In either case, we would want to abstract this type of failure (`[Local|Remote]DataStoreException`?), since the specific exceptions thrown are a detail of the local and remote data store implementations.

File: gnd/src/main/java/com/google/android/gnd/repository/DataRepository.java (hunk 3 above)
Comment (gino-m) [reply gnd/src/main/java/com/google/android/gnd/repository/DataRepository.java]: I've updated these to log failures so we can track which exceptions are relevant and update accordingly.

File: gnd/src/main/java/com/google/android/gnd/repository/DataRepository.java (hunk 2 above)
Comment (shobhitagarwal1612) [reply gnd/src/main/java/com/google/android/gnd/repository/DataRepository.java]: I don't know what other kinds of exceptions are thrown. This was based on my observation while targeting only internet availability as the culprit for the error.

File: .idea/codeStyles/Project.xml [hunk 4]
```diff
@@ -8,7 +8,6 @@
       </value>
     </option>
     <AndroidXmlCodeStyleSettings>
-      <option name="ARRANGEMENT_SETTINGS_MIGRATED_TO_191" value="true" />
```
Comment (shobhitagarwal1612) [inline .idea/codeStyles/Project.xml]: Might be worth keeping this if it the change is harmless.
