### PR TITLE
[Offline sync] Fix broken data sync

### LINKED ISSUE #177: [Offline sync] New features not synced to remote server
Stack trace:
```
2019-09-11 21:19:39.766 10558-10702/com.google.android.gnd D/LocalMutationSyncWorker: Remote updates for feature ThmJBl6ksh5yPz9oBrB8 failed
    java.lang.IllegalStateException: Cannot access database on the main thread since it may potentially lock the UI for a long period of time.
        at androidx.room.RoomDatabase.assertNotMainThread(RoomDatabase.java:261)
        at androidx.room.RoomDatabase.compileStatement(RoomDatabase.java:315)
        at com.google.android.gnd.persistence.local.room.FeatureMutationDao_Impl$6.call(FeatureMutationDao_Impl.java:258)
        at com.google.android.gnd.persistence.local.room.FeatureMutationDao_Impl$6.call(FeatureMutationDao_Impl.java:249)
        at io.reactivex.internal.operators.completable.CompletableFromCallable.subscribeActual(CompletableFromCallable.java:36)
        at io.reactivex.Completable.subscribe(Completable.java:2309)
        at com.akaita.java.rxjava2debug.extensions.CompletableOnAssembly.subscribeActual(CompletableOnAssembly.java:39)
        at io.reactivex.Completable.subscribe(Completable.java:2309)
        at io.reactivex.internal.operators.completable.CompletableAndThenCompletable.subscribeActual(CompletableAndThenCompletable.java:35)
        at io.reactivex.Completable.subscribe(Completable.java:2309)
        at com.akaita.java.rxjava2debug.extensions.CompletableOnAssembly.subscribeActual(CompletableOnAssembly.java:39)
        at io.reactivex.Completable.subscribe(Completable.java:2309)
        at io.reactivex.internal.operators.completable.CompletableAndThenCompletable$SourceObserver.onComplete(CompletableAndThenCompletable.java:67)
        at com.akaita.java.rxjava2debug.extensions.CompletableOnAssembly$OnAssemblyCompletableObserver.onComplete(CompletableOnAssembly.java:71)
        at io.reactivex.internal.operators.completable.CompletableCreate$Emitter.onComplete(CompletableCreate.java:64)
        at com.google.android.gnd.rx.RxTask.lambda$null$4(RxTask.java:74)
        at com.google.android.gnd.rx.-$$Lambda$RxTask$8seOJ-bOiPEAknEl_9ZxHw1hfSc.onSuccess(Unknown Source:2)
        at com.google.android.gms.tasks.zzn.run(Unknown Source:27)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: com.akaita.java.rxjava2debug.extensions.RxJavaAssemblyException
     Caused by: com.akaita.java.rxjava2debug.extensions.RxJavaAssemblyException
     Caused by: com.akaita.java.rxjava2debug.extensions.RxJavaAssemblyException
```

### PR DESCRIPTION
**Pull request by gino-m**
For some reason part of sync was trying to run on UI thread.

Fixes #177. Filed #178 to track longer term fix.

### CODE REVIEW

File: gnd/src/main/java/com/google/android/gnd/persistence/sync/LocalMutationSyncWorker.java [hunk 1]
```diff
@@ -77,9 +78,11 @@ public Result doWork() {
   }
 
   private Completable processMutations(ImmutableList<Mutation> pendingMutations) {
+    // TODO(#178): Why is removePendingMutations() getting run on UI thread without subscribeOn()?
```
Comment (scolsen) [inline gnd/src/main/java/com/google/android/gnd/persistence/sync/LocalMutationSyncWorker.java]: Looks like calling subscribeOn is a requirement for methods that return Maybe or Single:

> Room provides the option of observing the data in the database and performing asynchronous queries with the help of RxJava Maybe, Single and Flowable objects.
>
> If you’re worried about threads, Room keeps you at ease and ensures that observable queries are done off the main thread. It’s up to you to decide on which thread the events are emitted downstream, by setting the Scheduler in the observeOn method.
>
> For queries that return Maybe or Single, make sure you’re calling subscribeOn with a different Scheduler than AndroidSchedulers.mainThread().

From https://medium.com/androiddevelopers/room-rxjava-acb0cd4f3757

Comment (scolsen) [reply gnd/src/main/java/com/google/android/gnd/persistence/sync/LocalMutationSyncWorker.java]: @gino-m FYI
