### PR TITLE
Fix activeNetworkInfo Deprecation

### LINKED ISSUE #2967: activeNetworkInfo is Deprecated
```kt
   val networkInfo = cm.activeNetworkInfo
    return networkInfo?.isConnected ?: false
```

The activeNetworkInfo method in ConnectivityManager has been deprecated since API level 29 (Android 10).

### PR DESCRIPTION
**Pull request by anandwana001**
Fixes #2967 

Parent Ticket #2338 

This PR fixes the `activeNetworkInfo` deprecation by using `activeNetwork`

@shobhitagarwal1612  PTAL?

### CODE REVIEW

**Comment by shobhitagarwal1612** [comment]
Can you please add details on how you verified that no regressions are introduced with this change?

**Comment by anandwana001** [comment]
> Can you please add details on how you verified that no regressions are introduced with this change?


Manul testing, should we create a separate ticket for unit test network manager class?

**Comment by shobhitagarwal1612** [comment]
Some tests are failing, can you please look into it?

File: ground/src/main/java/com/google/android/ground/system/NetworkManager.kt [hunk 1]
```diff
@@ -61,11 +61,13 @@ class NetworkManager @Inject constructor(@ApplicationContext private val context
...
-  /** Returns true iff the device has internet connectivity, false otherwise. */
+  /** Returns true if the device has internet connectivity, false otherwise. */
   @RequiresPermission("android.permission.ACCESS_NETWORK_STATE")
   fun isNetworkConnected(): Boolean {
-    val cm = context.getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager
-    val networkInfo = cm.activeNetworkInfo
-    return networkInfo?.isConnected ?: false
+    val connectivityManager =
+      context.getSystemService(Context.CONNECTIVITY_SERVICE) as ConnectivityManager
+    val activeNetwork = connectivityManager.activeNetwork
```
Comment (shobhitagarwal1612) [inline ground/src/main/java/com/google/android/ground/system/NetworkManager.kt:69]: Can `activeNetwork` be null? If yes, can we add null check for safety?

File: ground/src/main/java/com/google/android/ground/system/NetworkManager.kt [hunk 2]
```diff
@@ -61,11 +61,13 @@ class NetworkManager @Inject constructor(@ApplicationContext private val context
...
+    val networkCapabilities = connectivityManager.getNetworkCapabilities(activeNetwork)
+    return networkCapabilities?.hasCapability(NET_CAPABILITY_INTERNET) == true
```
Comment (shobhitagarwal1612) [inline ground/src/main/java/com/google/android/ground/system/NetworkManager.kt:71]: Let's add a log with the result boolean value.

**Review by shobhitagarwal1612 — CHANGES_REQUESTED** [review]

File: ground/src/main/java/com/google/android/ground/system/NetworkManager.kt (hunk 1 above)
Comment (anandwana001) [reply ground/src/main/java/com/google/android/ground/system/NetworkManager.kt:69]: as the next LoC accepts null and eventually it will return false, so I think we don't need extra null check.

File: ground/src/main/java/com/google/android/ground/system/NetworkManager.kt (hunk 2 above)
Comment (shobhitagarwal1612) [reply ground/src/main/java/com/google/android/ground/system/NetworkManager.kt:71]: Yes. It would be helpful when debugging the app locally to understand how frequently the function is invoked or if it fails what was the last checked value.

File: ground/src/main/java/com/google/android/ground/system/NetworkManager.kt (hunk 1 above)
Comment (shobhitagarwal1612) [reply ground/src/main/java/com/google/android/ground/system/NetworkManager.kt:69]: SG

File: ground/src/main/java/com/google/android/ground/system/NetworkManager.kt (hunk 2 above)
Comment (shobhitagarwal1612) [inline ground/src/main/java/com/google/android/ground/system/NetworkManager.kt:71]: `== true` can be replaced with `?: false`

**Review by shobhitagarwal1612 — APPROVED** [review]
