### PR TITLE
[Offline sync] Fix storing loading project offline

### LINKED ISSUE #298: [Project activation] Can't reactivate project when opening app w/o network
**Describe the bug**
The "Project loading" progress dialog spins forever.

**To Reproduce**
1. Close the app
2. Turn on Airplane Mode
3. Reopen the app

### PR DESCRIPTION
**Pull request by gino-m**
Fixes #298. Depends on #293. Includes some small cleanup tasks done while debugging.

### CODE REVIEW

File: gnd/src/main/java/com/google/android/gnd/repository/ProjectRepository.java [hunk 1]
```diff
@@ -84,8 +84,14 @@ public ProjectRepository(
...
     return syncProjectWithRemote(id)
         .doOnSubscribe(__ -> Log.d(TAG, "Activating project " + id))
-        .doOnError(err -> Log.d(TAG, "Failed to load project from remote", err))
-        .onErrorResumeNext(__ -> localDataStore.getProjectById(id).toSingle())
+        .doOnError(err -> Log.d(TAG, "Error loading project from remote", err))
+        .onErrorResumeNext(
+            __ ->
+                localDataStore
+                    .getProjectById(id)
+                    .doOnComplete(() -> Log.d(TAG, "Project not found in local db"))
```
Comment (shobhitagarwal1612) [inline gnd/src/main/java/com/google/android/gnd/repository/ProjectRepository.java]: Please remove this

**Comment by gino-m** [comment]
Cloud Build was failing because it appears I missed a usage of RxJava2Debug. In hindsight, I realize removing it now was a little overzealous, so I've put it back and moved all initialization into `GndApplication`. Sorry for squeezing these cleanups into the same PR for the sake of expediency. I've committed each change separately, hopefully that helps split out the changes.
