### PR TITLE
SkippedTaskData instance check for taskData

### LINKED ISSUE #3217: [Data collection] Skipping last task crashes app
This also appears in Crashlytics (16 crashes in the last 7 days). @anandwana001 @shobhitagarwal1612 FYI

Log:

```
                                         java.lang.ClassCastException: org.groundplatform.android.model.submission.SkippedTaskData cannot be cast to org.groundplatform.android.model.submission.TextTaskData
                                         	at org.groundplatform.android.ui.datacollection.tasks.text.TextTaskViewModel.validate(TextTaskViewModel.kt:39)
                                         	at org.groundplatform.android.ui.datacollection.tasks.AbstractTaskViewModel.validate(AbstractTaskViewModel.kt:45)
                                         	at org.groundplatform.android.ui.datacollection.DataCollectionViewModel.onNextClicked(DataCollectionViewModel.kt:254)
                                         	at org.groundplatform.android.ui.datacollection.tasks.AbstractTaskFragment.moveToNext(AbstractTaskFragment.kt:190)
                                         	at org.groundplatform.android.ui.datacollection.tasks.AbstractTaskFragment.onSkip(AbstractTaskFragment.kt:182)
                                         	at org.groundplatform.android.ui.datacollection.tasks.AbstractTaskFragment.access$onSkip(AbstractTaskFragment.kt:50)
                                         	at org.groundplatform.android.ui.datacollection.tasks.AbstractTaskFragment$addSkipButton$1.invoke(AbstractTaskFragment.kt:173)
                                         	at org.groundplatform.android.ui.datacollection.tasks.AbstractTaskFragment$addSkipButton$1.invoke(AbstractTaskFragment.kt:173)
                                         	at org.groundplatform.android.ui.datacollection.components.TaskButton$CreateButton$7.invoke(TaskButton.kt:56)
                                         	at org.groundplatform.android.ui.datacollection.components.TaskButton$CreateButton$7.invoke(TaskButton.kt:54)
                                         	at androidx.compose.foundation.ClickableNode$clickPointerInput$3.invoke-k-4lQ0M(Clickable.kt:699)
                                         	at androidx.compose.foundation.ClickableNode$clickPointerInput$3.invoke(Clickable.kt:693)
                                         	at androidx.compose.foundation.gestures.TapGestureDetectorKt$detectTapAndPress$2$1.invokeSuspend(TapGestureDetector.kt:266)
                                         	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                         	at kotlinx.coroutines.DispatchedTaskKt.resume(DispatchedTask.kt:179)
                                         	at kotlinx.coroutines.DispatchedTaskKt.dispatch(DispatchedTask.kt:168)
                                         	at kotlinx.coroutines.CancellableContinuationImpl.dispatchResume(CancellableContinuationImpl.kt:474)
                                         	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl(CancellableContinuationImpl.kt:508)
                                         	at kotlinx.coroutines.CancellableContinuationImpl.resumeImpl$default(CancellableContinuationImpl.kt:497)
                                         	at kotlinx.coroutines.CancellableContinuationImpl.resumeWith(CancellableContinuationImpl.kt:368)
                                         	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl$PointerEventHandlerCoroutine.offerPointerEvent(SuspendingPointerInputFilter.kt:830)
                                         	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.dispatchPointerEvent(SuspendingPointerInputFilter.kt:698)
                                         	at androidx.compose.ui.input.pointer.SuspendingPointerInputModifierNodeImpl.onPointerEvent-H0pRuoY(SuspendingPointerInputFilter.kt:724)
                                         	at androidx.compose.foundation.AbstractClickableNode.onPointerEvent-H0pRuoY(Clickable.kt:1159)
                                         	at androidx.compose.ui.input.pointer.Node.dispatchMainEventPass(HitPathTracker.kt:436)
                                         	at androidx.compose.ui.input.pointer.NodeParent.dispatchMainEventPass(HitPathTracker.kt:275)
                                         	at androidx.compose.ui.input.pointer.HitPathTracker.dispatchChanges(HitPathTracker.kt:171)
                                         	at androidx.compose.ui.input.pointer.PointerInputEventProcessor.process-BIzXfog(PointerInputEventProcessor.kt:117)
                                         	at androidx.compose.ui.platform.AndroidComposeView.sendMotionEvent-8iAsVTc(AndroidComposeView.android.kt:2363)
                                         	at androidx.compose.ui.platform.AndroidComposeView.handleMotionEvent-8iAsVTc(AndroidComposeView.android.kt:2313)
                                         	at androidx.compose.ui.platform.AndroidComposeView.dispatchTouchEvent(AndroidComposeView.android.kt:2184)
                                         	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
                                         	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
                                         	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
                                         	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
                                         	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
13:50:58.172 AndroidRuntime           E  	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801) (Ask Gemini)
                                         	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
                                         	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
                                         	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
                                         	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
                                         	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
                                         	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
                                         	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
                                         	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
                                         	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
                                         	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
                                         	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
                                         	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
                                         	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
                                         	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
                                         	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
                                         	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
                                         	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
                                         	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
                                         	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
                                         	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
                                         	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
                                         	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
                                         	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:3120)
                                         	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2801)
                                         	at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:490)
                                         	at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1904)
                                         	at android.app.Activity.dispatchTouchEvent(Activity.java:4377)
                                         	at androidx.appcompat.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:69)
                                         	at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:448)
                                         	at android.view.View.dispatchPointerEvent(View.java:15919)
                                         	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:7021)
                                         	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:6815)
                                         	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6229)
                                         	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6286)
                                         	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6252)
                                         	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:6417)
                                         	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6260)
                                         	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:6474)
                                         	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6233)
                                         	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:6286)
                                         	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:6252)
                                         	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:6260)
                                         	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:6233)
                                         	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:9211)
                                         	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:9162)
                                         	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:9131)
                                         	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:9337)
                                         	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:267)
                                         	at android.os.MessageQueue.nativePollOnce(Native Method)
                                         	at android.os.MessageQueue.next(MessageQueue.java:335)
                                         	at android.os.Looper.loopOnce(Looper.java:162)
                                         	at android.os.Looper.loop(Looper.java:294)
                                         	at android.app.ActivityThread.main(ActivityThread.java:8177)
                                         	at java.lang.reflect.Method.invoke(Native Method)
13:50:58.172 AndroidRuntime           E  	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552) (Ask Gemini)
                                         	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                                         	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.platform.MotionDurationScaleImpl@2c13147, androidx.compose.runtime.BroadcastFrameClock@d2fcd74, StandaloneCoroutine{Cancelling}@9ac029d, AndroidUiDispatcher@9772312]
```

@vittorino What should the UX be here?

### PR DESCRIPTION
**Pull request by anandwana001**
Fixes #3217

@shobhitagarwal1612  PTAL?

### CODE REVIEW

File: app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/text/TextTaskViewModel.kt [hunk 1]
```diff
@@ -36,8 +36,10 @@ class TextTaskViewModel @Inject constructor() : AbstractTaskViewModel() {
   override fun validate(task: Task, taskData: TaskData?): Int? {
     if (task.type != Task.Type.TEXT) return super.validate(task, taskData)
 
-    if ((taskData as TextTaskData).text.length > Constants.TEXT_DATA_CHAR_LIMIT)
```
Comment (shobhitagarwal1612) [inline app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/text/TextTaskViewModel.kt:39]: Shouldn't we add a check if the tasks data is of type skipped at the calling place to handle this problem across all tasks?

**Review by shobhitagarwal1612 — CHANGES_REQUESTED** [review]
Can we add some unit test coverage for this bug?

File: app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/text/TextTaskViewModel.kt (hunk 1 above)
Comment (shobhitagarwal1612) [reply app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/text/TextTaskViewModel.kt:39]: Is this resolved?

**Comment by rfontanarosa** [comment]
tested. it works.

File: app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/text/TextTaskViewModel.kt (hunk 1 above)
Comment (anandwana001) [reply app/src/main/java/org/groundplatform/android/ui/datacollection/tasks/text/TextTaskViewModel.kt:39]: yes, tested by keeping all other task and skipping them, all other already have proper checks so working fine.

**Review by shobhitagarwal1612 — APPROVED** [review]
