### PR TITLE
Fix NoSuchElementException in getTaskViewModel by Handling Empty Collection

### LINKED ISSUE #2998: getTaskViewModel - Collection contains no element matching the predicate.
```
Caused by java.util.NoSuchElementException: Collection contains no element matching the predicate.
       at com.google.android.ground.ui.datacollection.DataCollectionViewModel.getTaskViewModel(DataCollectionViewModel.kt:467)
       at com.google.android.ground.ui.datacollection.DataCollectionViewModel.saveCurrentState(DataCollectionViewModel.kt:252)
       at com.google.android.ground.ui.datacollection.DataCollectionFragment.onPause(DataCollectionFragment.kt:117)
       at androidx.fragment.app.Fragment.performPause(Fragment.java:3330)
       at androidx.fragment.app.FragmentStateManager.pause(FragmentStateManager.java:692)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:318)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1675)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3259)
       at androidx.fragment.app.FragmentManager.dispatchPause(FragmentManager.java:3195)
       at androidx.fragment.app.Fragment.performPause(Fragment.java:3323)
       at androidx.fragment.app.FragmentStateManager.pause(FragmentStateManager.java:692)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:318)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1675)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3259)
       at androidx.fragment.app.FragmentManager.dispatchPause(FragmentManager.java:3195)
       at androidx.fragment.app.FragmentController.dispatchPause(FragmentController.java:296)
       at androidx.fragment.app.FragmentActivity.onPause(FragmentActivity.java:284)
       at com.google.android.ground.AbstractActivity.onPause(AbstractActivity.kt:63)
       at android.app.Activity.performPause(Activity.java:8870)
       at android.app.Instrumentation.callActivityOnPause(Instrumentation.java:1618)
       at android.app.ActivityThread.performPauseActivityIfNeeded(ActivityThread.java:5722)
       at android.app.ActivityThread.performPauseActivity(ActivityThread.java:5683)
       at android.app.ActivityThread.handlePauseActivity(ActivityThread.java:5635)
       at android.app.servertransaction.PauseActivityItem.execute(PauseActivityItem.java:47)
       at android.app.servertransaction.ActivityTransactionItem.execute(ActivityTransactionItem.java:45)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:176)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2584)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:226)
       at android.os.Looper.loop(Looper.java:313)
       at android.app.ActivityThread.main(ActivityThread.java:8810)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:604)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1067)
        
```

### PR DESCRIPTION
**Pull request by anandwana001**
Fixes #2998 

@shobhitagarwal1612  PTAL?

### CODE REVIEW

File: app/src/main/java/org/groundplatform/android/ui/datacollection/DataCollectionViewModel.kt [hunk 1]
```diff
@@ -197,23 +197,23 @@ internal constructor(
   fun getTaskViewModel(taskId: String): AbstractTaskViewModel? {
     val viewModels = taskViewModels.value
 
-    val task = tasks.first { it.id == taskId }
-
-    if (viewModels.containsKey(taskId)) {
-      return viewModels[taskId]
-    }
```
Comment (shobhitagarwal1612) [inline app/src/main/java/org/groundplatform/android/ui/datacollection/DataCollectionViewModel.kt:204]: Can this be moved outside of the modified logic since it is not dependent upon the `task` variable?

File: app/src/main/java/org/groundplatform/android/ui/datacollection/DataCollectionViewModel.kt [hunk 2]
```diff
@@ -197,23 +197,24 @@ internal constructor(
...
-
-      val taskData: TaskData? = if (shouldLoadFromDraft) getValueFromDraft(task) else null
-      viewModel.initialize(job, task, taskData)
-      viewModel
-    } catch (e: Exception) {
-      Timber.e("ignoring task with invalid type: $task.type")
-      null
-    }
+    return tasks
+      .firstOrNull { it.id == taskId }
```
Comment (shobhitagarwal1612) [inline app/src/main/java/org/groundplatform/android/ui/datacollection/DataCollectionViewModel.kt:205]: We can simplify the nesting by returning early. Then the rest of the code can remain flattened.

```
val task = tasks.firstOrNull { it.id == taskId } ?: return null
...
```

Comment (anandwana001) [reply app/src/main/java/org/groundplatform/android/ui/datacollection/DataCollectionViewModel.kt:205]: the number of return statement is increaseing hence did this.

Comment (shobhitagarwal1612) [reply app/src/main/java/org/groundplatform/android/ui/datacollection/DataCollectionViewModel.kt:205]: Is that causing any lint errors?

Comment (anandwana001) [reply app/src/main/java/org/groundplatform/android/ui/datacollection/DataCollectionViewModel.kt:205]: Yes

**Review by shobhitagarwal1612 — APPROVED** [review]

File: app/src/main/java/org/groundplatform/android/ui/datacollection/DataCollectionViewModel.kt (hunk 2 above)
Comment (gino-m) [inline app/src/main/java/org/groundplatform/android/ui/datacollection/DataCollectionViewModel.kt:205]: Why would we displaying the data collection interface if there are no tasks, or why would we be requesting a taskId which doesn't existing? Is there a race condition somewhere?

**Comment by gino-m** [comment]
Note that this PR as-is doesn't address and hides the root cause. @anandwana001 is looking into this further.

File: app/src/main/java/org/groundplatform/android/ui/datacollection/DataCollectionViewModel.kt [hunk 3]
```diff
@@ -203,23 +203,24 @@ internal constructor(
...
+      ?.let { task ->
+        try {
+          viewModelFactory.create(getViewModelClass(task.type)).apply {
+            taskViewModels.value[task.id] = this
+            val taskData: TaskData? = if (shouldLoadFromDraft) getValueFromDraft(task) else null
+            initialize(job, task, taskData)
+          }
+        } catch (e: Exception) {
+          Timber.e("Ignoring task with invalid type: ${task.type}")
```
Comment (gino-m) [inline app/src/main/java/org/groundplatform/android/ui/datacollection/DataCollectionViewModel.kt:220]: This reports _any_ Exception as being caused by "invalid type". Is that actually true? Instead, why not report the error with a more generic message, for ex:

`Timber.e(e, "Failed to initialize task view model for task ${task.id}")`

File: app/src/main/java/org/groundplatform/android/ui/datacollection/DataCollectionViewModel.kt [hunk 4]
```diff
@@ -203,23 +203,24 @@ internal constructor(
...
-      taskViewModels.value[task.id] = viewModel
-
-      val taskData: TaskData? = if (shouldLoadFromDraft) getValueFromDraft(task) else null
-      viewModel.initialize(job, task, taskData)
-      viewModel
-    } catch (e: Exception) {
-      Timber.e("ignoring task with invalid type: $task.type")
-      null
-    }
+    return tasks
```
Comment (gino-m) [inline app/src/main/java/org/groundplatform/android/ui/datacollection/DataCollectionViewModel.kt:210]: Should we also log an error if there are more than one task with the same ID?

File: app/src/main/java/org/groundplatform/android/ui/datacollection/DataCollectionViewModel.kt [hunk 5]
```diff
@@ -203,23 +203,24 @@ internal constructor(
...
+      .firstOrNull { it.id == taskId }
```
Comment (gino-m) [inline app/src/main/java/org/groundplatform/android/ui/datacollection/DataCollectionViewModel.kt:211]: And we should log an error if we're looking for a task which doesn't exist as well.

File: app/src/main/java/org/groundplatform/android/ui/datacollection/DataCollectionViewModel.kt [hunk 6]
```diff
@@ -203,23 +203,24 @@ internal constructor(
...
+      ?.let { task ->
+        try {
```
Comment (gino-m) [inline app/src/main/java/org/groundplatform/android/ui/datacollection/DataCollectionViewModel.kt:213]: There's a lot of nesting here, making the code harder to follow than necessary. When resolving other comments please see if this can be simplified.

**Review by gino-m — DISMISSED** [review]

**Comment by gino-m** [comment]
@anandwana001 Do we understand why the `tasks` collection is empty, and how to fix it?

**Comment by anandwana001** [comment]
> @anandwana001 Do we understand why the `tasks` collection is empty, and how to fix it?

As per the discussion https://github.com/google/ground-android/issues/2998#issuecomment-2652854462, we are doing the error logging and returning empty ViewModel.

**Comment by gino-m** [comment]
> > @anandwana001 Do we understand why the `tasks` collection is empty, and how to fix it?
> 
> As per the discussion [#2998 (comment)](https://github.com/google/ground-android/issues/2998#issuecomment-2652854462), we are doing the error logging and returning empty ViewModel.

Swallowing the error and continuing as if nothing happened is not a valid approach, since if this occurs it means the app is in an invalid state. I recommend rolling back this change and identifying the root cause for why the `tasks` collection might be empty.
