### PR TITLE
Fix flickering of offline icon in survey selector screen

### LINKED ISSUE #2558: Offline and overflow icon in Survey Selector screen flickers on load
Steps to reproduce:

1. Open survey selector screen
2. Observe that `offline` and `overflow` icons are visible for all cards and then disappear

Expected behavior: 

1. No flickering should happen

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Fixes #2558

Due to data binding, there was a delay in offline icon's visibility change. Doing it manually resolves the issue.

[Before](https://github.com/user-attachments/assets/065375ae-c91f-460c-bb86-1a69146dca4a)

[After](https://github.com/user-attachments/assets/392acf70-e278-4385-90ed-f8d3576c8e4d)

@gino-m  PTAL?

### CODE REVIEW

File: ground/src/main/java/com/google/android/ground/ui/surveyselector/SurveyListAdapter.kt [hunk 1]
```diff
@@ -42,10 +43,17 @@ class SurveyListAdapter(
...
+    with(holder.binding) {
+      val me = this@SurveyListAdapter
+      item = surveyListItem
+      viewModel = me.viewModel
+      fragment = me.fragment
+
+      val offlineVisibility = if (surveyListItem.availableOffline) View.VISIBLE else View.GONE
+      offlineIcon.visibility = offlineVisibility
+      overflowMenu.visibility = offlineVisibility
+    }
```
Comment (anandwana001) [inline ground/src/main/java/com/google/android/ground/ui/surveyselector/SurveyListAdapter.kt:56]: just a quick guess, but how about if we take the BindingAdapter annotation approach over here?

WDYT?

IMO, onBindViewHolder should be a mediator type, it should not consist the UI logics.

Comment (shobhitagarwal1612) [reply ground/src/main/java/com/google/android/ground/ui/surveyselector/SurveyListAdapter.kt:56]: We already had the bind adaptor approach which was leading to this problem. Given that we are moving towards jetpack compose, this recycler view / view holder should get replaced soon in the future with the migration.

**Review by sufyanAbbasi — APPROVED** [review]
Thank you!
