### PR TITLE
[Offline sync] Fix bugs on save observation

### LINKED ISSUE #249: [Observation list] Add observation button disappears on back
This occurs after adding, editing, or viewing an observation

### LINKED ISSUE #250: [Add/edit observation] Some values missing after saving
After saving a new/existing observation, done fields appear blank in the observation list and observation details fragment. Closing and opening the feature details sheet causes the actual values to appear.

### LINKED ISSUE #256: [Offline sync] Cleared fields gets reverted on sync
1. Turn on Airplane Mode
1. Add and save an observation
1. Edit the observation and delete a value so that the field is blank
1. Turn off Airplane Mode
1. Data syncs, cleared field returns

### PR DESCRIPTION
**Pull request by gino-m**
Fixes #250, fixes #249, fixes #256, depends on #246. See individual commits for actual delta. Please merge #246 first.

### CODE REVIEW

**Comment by gino-m** [comment]
@scolsen @shobhitagarwal1612 @deepakbansal Could one of you kindly give this a quick review?

**Comment by shobhitagarwal1612** [comment]
> Fixes #250, #249, #256. Depends on #246. See individual commits for actual delta. Please merge #246 first.

Quick comment: We need to mention `Fixes or Closes` before each PR number to close it automatically. So, it should be `Fixes #250, Fixes #249, Fixes #256`

**Comment by gino-m** [comment]
> Quick comment: We need to mention `Fixes or Closes` before each PR number to close it automatically. So, it should be `Fixes #250, Fixes #249, Fixes #256`

Good catch, fixed!

**Comment by gino-m** [comment]
@scolsen Could you PTAL?

**Comment by shobhitagarwal1612** [comment]
I was waiting for #246 to get merged before reviewing this as mentioned in the description.

**Comment by gino-m** [comment]
> I was waiting for #246 to get merged before reviewing this as mentioned in the description.

I can be reviewed now, we just need to wait for #246 before we merge. In either case it's ok, just making sure it's in someone's queue. Thanks!!

**Comment by gino-m** [comment]
> @scolsen Could you PTAL?

Please disregard! :) Thanks @shobhitagarwal1612 !

**Comment by gino-m** [comment]
@shobhitagarwal1612 Resolved conflicts manually, hopefully will pass CI. PTAL!

File: gnd/src/main/java/com/google/android/gnd/repository/DataRepository.java [hunk 1]
```diff
@@ -143,6 +144,14 @@ private void onProjectLoaded(Project project) {
     localValueStore.setLastActiveProjectId(project.getId());
   }
 
+  private Single<List<Project>> loadProjects(User user) {
```
Comment (shobhitagarwal1612) [inline gnd/src/main/java/com/google/android/gnd/repository/DataRepository.java]: This can be removed

File: gnd/src/main/java/com/google/android/gnd/repository/DataRepository.java [hunk 2]
```diff
@@ -265,7 +274,6 @@ public Completable saveFeature(Feature feature) {
                 .build())
         .andThen(dataSyncWorkManager.enqueueSyncWorker(feature.getId()));
   }
-
```
Comment (shobhitagarwal1612) [inline gnd/src/main/java/com/google/android/gnd/repository/DataRepository.java]: Please add back this line

File: gnd/src/main/java/com/google/android/gnd/repository/DataRepository.java (hunk 1 above)
Comment (shobhitagarwal1612) [reply gnd/src/main/java/com/google/android/gnd/repository/DataRepository.java]: Never mind! I pushed a fix

**Comment by shobhitagarwal1612** [comment]
The build is passing now but CLA is failing for some reason.

**Comment by gino-m** [comment]
> The build is passing now but CLA is failing for some reason.

I did some digging and it seems this happens when there are multiple PR authors. I'll set the `cla: yes` tag now to force CLA check.
