### PR TITLE
Fix LocationOfInterest display name

### LINKED ISSUE #1559: LocationOfInterest caption and customId inconsistently implemented
- [ ] Update `LoiDocument` and `LocationOfInterest` to include `properties: Map<String, Object>`
- [ ] Update `LoiConverter` to copy these over
- [ ] Similarly, update `LocationOfInterestEntity` and related converter for local data store
- [ ] Remove `caption` field from all above Loi impls
- [ ] Update `LoiCardUtil.getDisplayLoiName` to use Feature `customId` field for LOI id. If customId isn't present, look for property named `id`.
- [ ] Use `name` property as label if present using format described in https://github.com/google/ground-platform/issues/1242

Related to https://github.com/google/ground-platform/issues/997

### PR DESCRIPTION
**Pull request by rachaprince**
Fixes #1559

Update the way LOI customId and properties fields are used to display the LOI 

Screenshot 2023-11-06 at 1 25 14 PM
Screenshot 2023-11-06 at 12 51 53 PM
Screenshot 2023-11-06 at 1 26 49 PM
@gino-m  PTAL?

### CODE REVIEW

File: ground/src/main/java/com/google/android/ground/model/locationofinterest/LocationOfInterest.kt [hunk 1]
```diff
@@ -51,7 +49,9 @@ data class LocationOfInterest(
    * Whether this LOI was created opportunistically by the user through the Suggest LOI flow, or
    * false if the LOI was created by the survey organizer.
    */
-  val isOpportunistic: Boolean = false
+  val isOpportunistic: Boolean = false,
+  /** Custom map of properties for this LOI. Corresponds to the properties field in GeoJSON */
+  val properties: Map<String, Any>? = null,
```
Comment (gino-m) [inline ground/src/main/java/com/google/android/ground/model/locationofinterest/LocationOfInterest.kt:54]: Can we define this type as a typealias? Perhaps `LocationOfInterest.Properties`?

Comment (gino-m) [inline ground/src/main/java/com/google/android/ground/model/locationofinterest/LocationOfInterest.kt:54]: Also, to avoid dual nil states (empty vs null), can we make this non-null and default to empty map in the local and remote Converters if not set in persistent storage?

File: ground/src/main/java/com/google/android/ground/model/mutation/LocationOfInterestMutation.kt [hunk 2]
```diff
@@ -29,9 +29,10 @@ data class LocationOfInterestMutation(
...
   override val lastError: String = "",
   val jobId: String = "",
+  val customId: String? = null,
   val geometry: Geometry? = null,
-  val caption: String? = null,
   val submissionCount: Int = 0,
   val ownerEmail: String? = null,
-  val isOpportunistic: Boolean = false
+  val isOpportunistic: Boolean = false,
+  val properties: Map<String, Any>? = null,
```
Comment (gino-m) [inline ground/src/main/java/com/google/android/ground/model/mutation/LocationOfInterestMutation.kt:37]: Same here

File: ground/src/main/java/com/google/android/ground/model/mutation/LocationOfInterestMutation.kt [hunk 3]
```diff
@@ -29,9 +29,10 @@ data class LocationOfInterestMutation(
   override val retryCount: Long = 0,
   override val lastError: String = "",
   val jobId: String = "",
+  val customId: String? = null,
```
Comment (gino-m) [inline ground/src/main/java/com/google/android/ground/model/mutation/LocationOfInterestMutation.kt:32]: Can we default to empty string and make non-null?

File: ground/src/main/java/com/google/android/ground/persistence/local/room/converter/LoiPropertiesMapConverter.kt [hunk 4]
```diff
@@ -0,0 +1,45 @@
+package com.google.android.ground.persistence.local.room.converter
```
Comment (gino-m) [inline ground/src/main/java/com/google/android/ground/persistence/local/room/converter/LoiPropertiesMapConverter.kt:1]: Please add copyright header to new files

File: ground/src/main/java/com/google/android/ground/persistence/local/room/converter/LoiPropertiesMapConverter.kt [hunk 5]
```diff
@@ -0,0 +1,45 @@
...
+import kotlinx.collections.immutable.toPersistentMap
+import org.json.JSONException
+import org.json.JSONObject
+import timber.log.Timber
+
+
+object LoiPropertiesMapConverter {
+  @TypeConverter
+  fun toString(properties: Map<String, Any>?): String? {
+    if (properties ==null) {
```
Comment (gino-m) [inline ground/src/main/java/com/google/android/ground/persistence/local/room/converter/LoiPropertiesMapConverter.kt:16]: Nit: Run gradle ktfmtFormat (also avail in Gradle pane in Android Studio) to autoformat.

Comment (gino-m) [reply ground/src/main/java/com/google/android/ground/persistence/local/room/converter/LoiPropertiesMapConverter.kt:16]: To avoid needing to handle both empty and null states, can we make these non-null and default to empty?

File: ground/src/main/java/com/google/android/ground/persistence/local/room/converter/LoiPropertiesMapConverter.kt [hunk 6]
```diff
@@ -0,0 +1,45 @@
...
+    try {
+      jsonString =  JSONObject(properties).toString()
+    } catch (e: JSONException) {
+      Timber.e(e, "Error building JSON")
+    }
+    return jsonString
+  }
+
+  @TypeConverter
+  fun fromString(jsonString: String?): Map<String, Any> {
```
Comment (gino-m) [inline ground/src/main/java/com/google/android/ground/persistence/local/room/converter/LoiPropertiesMapConverter.kt:29]: Same here

File: ground/src/main/java/com/google/android/ground/persistence/local/room/converter/LoiPropertiesMapConverter.kt [hunk 7]
```diff
@@ -0,0 +1,45 @@
...
+    if (jsonString == null) {
+      return mapOf()
+    }
+    var map = mutableMapOf<String, Any>()
+    try {
+      val type = object: TypeToken<Map<String, Any>>(){}.type
+      map = Gson().fromJson(
```
Comment (gino-m) [inline ground/src/main/java/com/google/android/ground/persistence/local/room/converter/LoiPropertiesMapConverter.kt:36]: @JSunde introduce proto (de)serialization for local storage. Can we use that instead of packing/unpacking Json ourselves?

File: ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/LoiDocument.kt [hunk 8]
```diff
@@ -24,11 +24,11 @@ import com.google.firebase.firestore.IgnoreExtraProperties
...
   val customId: String? = null,
-  val caption: String? = null,
   val location: GeoPoint? = null,
   val geoJson: String? = null,
   val geometry: Map<String, Any>? = null,
   val created: AuditInfoNestedObject? = null,
   val lastModified: AuditInfoNestedObject? = null,
-  val submissionCount: Int? = null
+  val submissionCount: Int? = null,
+  val properties: Map<String, Any>? = null,
```
Comment (gino-m) [inline ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/LoiDocument.kt:33]: Note: In this case my previous comments about null vs empty doesn't apply since we need to fail gracefully when these are null on remote.

**Review by gino-m — CHANGES_REQUESTED** [review]
So excited to finally see this working! A few nits, overall LGTM!

File: ground/src/main/java/com/google/android/ground/persistence/local/room/converter/LoiPropertiesMapConverter.kt (hunk 5 above)
Comment (rachaprince) [reply ground/src/main/java/com/google/android/ground/persistence/local/room/converter/LoiPropertiesMapConverter.kt]: Done

File: ground/src/main/java/com/google/android/ground/persistence/local/room/converter/LoiPropertiesMapConverter.kt (hunk 7 above)
Comment (rachaprince) [reply ground/src/main/java/com/google/android/ground/persistence/local/room/converter/LoiPropertiesMapConverter.kt]: Is this referring to JsonObjectTypeConverter?

File: ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/LoiDocument.kt (hunk 8 above)
Comment (rachaprince) [reply ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/LoiDocument.kt]: Makes sense!

File: ground/src/main/java/com/google/android/ground/persistence/local/room/converter/LoiPropertiesMapConverter.kt (hunk 6 above)
Comment (rachaprince) [reply ground/src/main/java/com/google/android/ground/persistence/local/room/converter/LoiPropertiesMapConverter.kt]: Done

File: ground/src/main/java/com/google/android/ground/persistence/local/room/converter/LoiPropertiesMapConverter.kt (hunk 4 above)
Comment (rachaprince) [reply ground/src/main/java/com/google/android/ground/persistence/local/room/converter/LoiPropertiesMapConverter.kt:16]: Done

File: ground/src/main/java/com/google/android/ground/model/mutation/LocationOfInterestMutation.kt (hunk 2 above)
Comment (rachaprince) [reply ground/src/main/java/com/google/android/ground/model/mutation/LocationOfInterestMutation.kt]: Done

File: ground/src/main/java/com/google/android/ground/model/mutation/LocationOfInterestMutation.kt (hunk 3 above)
Comment (rachaprince) [reply ground/src/main/java/com/google/android/ground/model/mutation/LocationOfInterestMutation.kt]: Done

File: ground/src/main/java/com/google/android/ground/model/locationofinterest/LocationOfInterest.kt (hunk 1 above)
Comment (rachaprince) [reply ground/src/main/java/com/google/android/ground/model/locationofinterest/LocationOfInterest.kt]: Done

File: ground/src/main/java/com/google/android/ground/persistence/local/room/converter/LoiPropertiesMapConverter.kt (hunk 7 above)
Comment (gino-m) [reply ground/src/main/java/com/google/android/ground/persistence/local/room/converter/LoiPropertiesMapConverter.kt]: It's being done in `GeometryWrapperTypeConverter` using`ProtoBuf.encodeToByteArray()`. Can we use the same here?

Comment (rachaprince) [reply ground/src/main/java/com/google/android/ground/persistence/local/room/converter/LoiPropertiesMapConverter.kt]: Hmmm so using ProtoBuf.encodeToByteArray() throws a Serialization Exception because kotlin doesn't have a serializer for the Any class http://screen/H4ovCcLxGR3MvZA

This medium article suggests either creating a custom serializer, or defining a stricter type, or using Gson. https://medium.com/@kerem_balic/serializer-for-class-any-not-found-how-do-we-fix-it-in-kotlin-cc196d92b7b3

What are your thoughts?

Comment (gino-m) [reply ground/src/main/java/com/google/android/ground/persistence/local/room/converter/LoiPropertiesMapConverter.kt]: Yikes, sorry I hadn't thought of that. Since we're adding properties to the model, perhaps now would be a good time to add stricter typing? Afaik there are only two possible types for properties values: `String` and `Number`. 

Assume the proto serializer can handle generics, can we define an interface `PropertyValue<T>` with one member `T value`, which is implemented by `NumberValue: PropertyValue<Number>` and `StringValue: PropertyValue<String>`?

**Review by gino-m — APPROVED** [review]
LG, thanks for the fix!

File: ground/src/main/java/com/google/android/ground/persistence/local/room/converter/LoiPropertiesMapConverter.kt (hunk 7 above)
Comment (gino-m) [reply ground/src/main/java/com/google/android/ground/persistence/local/room/converter/LoiPropertiesMapConverter.kt]: We chatted. We can make this change in a follow-up PR!

**Review by gino-m — APPROVED** [review]

**Comment by gino-m** [comment]
@rachaprince Looks like unit tests are failing. Relevant build log lines:

```
com.google.android.ground.ui.home.mapcontainer.LoiCardUtilTest > testArea_whenCustomIdIsNotAvailable_usesPropertiesId FAILED
    com.google.common.truth.ComparisonFailureWithFacts at LoiCardUtilTest.kt:66

383 tests completed, 1 failed

> Task :ground:testDevDebugUnitTest FAILED
```
