### PR TITLE
Fix “Canvas: trying to draw too large bitmap” by loading images with Glide (downsampling + EXIF auto-rotate)

### LINKED ISSUE #3232: Canvas: trying to draw too large(199756800bytes) bitmap.
```console
 Fatal Exception: java.lang.RuntimeException: Canvas: trying to draw too large(199756800bytes) bitmap.
       at android.graphics.RecordingCanvas.throwIfCannotDraw(RecordingCanvas.java:267)
       at android.graphics.BaseRecordingCanvas.drawBitmap(BaseRecordingCanvas.java:98)
       at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:561)
       at android.widget.ImageView.onDraw(ImageView.java:1446)
       at android.view.View.draw(View.java:25177)
       at android.view.View.updateDisplayListIfDirty(View.java:24036)
       at android.view.View.draw(View.java:24907)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
       at android.view.View.updateDisplayListIfDirty(View.java:24022)
       at android.view.View.draw(View.java:24907)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
       at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2082)
       at android.view.View.updateDisplayListIfDirty(View.java:24022)
       at android.view.View.draw(View.java:24907)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
       at android.view.View.updateDisplayListIfDirty(View.java:24022)
       at android.view.View.draw(View.java:24907)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
       at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2082)
       at android.view.View.updateDisplayListIfDirty(View.java:24022)
       at android.view.View.draw(View.java:24907)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
       at android.view.View.updateDisplayListIfDirty(View.java:24022)
       at android.view.View.draw(View.java:24907)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
       at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:5030)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
       at android.view.View.draw(View.java:25180)
       at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4429)
       at android.view.View.updateDisplayListIfDirty(View.java:24036)
       at android.view.View.draw(View.java:24907)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
       at android.view.View.updateDisplayListIfDirty(View.java:24022)
       at android.view.View.draw(View.java:24907)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
       at androidx.constraintlayout.widget.ConstraintLayout.dispatchDraw(ConstraintLayout.java:2082)
       at android.view.View.updateDisplayListIfDirty(View.java:24022)
       at android.view.View.draw(View.java:24907)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
       at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.kt:232)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
       at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.kt:222)
       at android.view.View.updateDisplayListIfDirty(View.java:24022)
       at android.view.View.draw(View.java:24907)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
       at androidx.fragment.app.FragmentContainerView.drawChild(FragmentContainerView.kt:232)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
       at androidx.fragment.app.FragmentContainerView.dispatchDraw(FragmentContainerView.kt:222)
       at android.view.View.updateDisplayListIfDirty(View.java:24022)
       at android.view.View.draw(View.java:24907)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
       at android.view.View.updateDisplayListIfDirty(View.java:24022)
       at android.view.View.draw(View.java:24907)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
       at android.view.View.updateDisplayListIfDirty(View.java:24022)
       at android.view.View.draw(View.java:24907)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
       at android.view.View.updateDisplayListIfDirty(View.java:24022)
       at android.view.View.draw(View.java:24907)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
       at android.view.View.updateDisplayListIfDirty(View.java:24022)
       at android.view.View.draw(View.java:24907)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
       at android.view.View.updateDisplayListIfDirty(View.java:24022)
       at android.view.View.draw(View.java:24907)
       at android.view.ViewGroup.drawChild(ViewGroup.java:4780)
       at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4538)
       at com.android.internal.policy.DecorView.dispatchDraw(DecorView.java:1179)
       at android.view.View.draw(View.java:25180)
       at com.android.internal.policy.DecorView.draw(DecorView.java:1161)
       at android.view.View.updateDisplayListIfDirty(View.java:24036)
       at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:768)
       at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:774)
       at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:872)
       at android.view.ViewRootImpl.draw(ViewRootImpl.java:6051)
       at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:5706)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:4795)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:3288)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:11344)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1689)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1698)
       at android.view.Choreographer.doCallbacks(Choreographer.java:1153)
       at android.view.Choreographer.doFrame(Choreographer.java:1079)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1646)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8919)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
        
```

decoding and returning the full-resolution image, then creating a full-resolution rotated copy, and handing that giant bitmap to the ImageView with no downsampling or clamping. (This earlier picaso use to handle)

On large photos (e.g., ~8000×6240), ARGB_8888 = w*h*4 bytes ≈ 49,939,200 * 4 ≈ 199,756,800 bytes — exactly the size in our crash. Canvas refuses to draw bitmaps that large.

https://github.com/google/ground-android/issues/3232

BitmapFactory.decodeStream(inputStream) → decodes full size.

Bitmap.createBitmap(bitmap, …, matrix, true) → makes a second full-size copy for rotation (original not recycled), doubling temporary memory and still leaving us with a massive bitmap to draw.

No sampling (inSampleSize) to match view/screen size; no final clamp.

So the root cause is unbounded, full-res decode + full-res rotate.

Picasso (like Glide/Coil) can prevent this crash because it:

Downscales before decode when we tell it the target size, and
Respects EXIF rotation (so we don’t need to rotate manually).

### PR DESCRIPTION
**Pull request by anandwana001**
Fixes #3232 

This PR replaces our manual bitmap decode/rotate path in the imageUri BindingAdapter with Glide, ensuring images are downsampled to the view (or half-screen) size and automatically rotated via EXIF. This prevents OOM/Canvas crashes when users capture high-resolution photos.

### What changed

-Use Glide in bindUri(imageUri):
   - `.override(targetW, targetH)` with a hard cap of 2048x2048
   - `.fitCenter()` to preserve aspect ratio without upscaling
   - `.downsample(DownsampleStrategy.AT_MOST)` to keep memory small
   - `.error(R.drawable.outline_error_outline_24)` for graceful fallback
   - Rely on Glide’s EXIF handling (no manual ExifInterface/Matrix).

### Why

Previous code decoded full-resolution images and then created a full-res rotated copy, causing:
- RuntimeException: Canvas: trying to draw too large (...) bitmap
- High memory usage / potential OOMs
- Glide decodes at (or below) target size and applies EXIF rotation internally.

### Before vs After

Before
- Full-size decode (BitmapFactory.decodeStream)
- Manual rotation via Matrix
- No size cap → crashes on very large photos

After
- Downsampled decode to view/half-screen size (max 2048)
- Automatic EXIF rotation (no extra copy)
- Stable memory footprint; no large-bitmap crash

@gino-m  PTAL?

### CODE REVIEW

File: app/src/main/java/org/groundplatform/android/ui/common/BindingAdapters.kt [hunk 1]
```diff
@@ -73,16 +72,17 @@ object BindingAdapters {
...
-    } catch (e: IOException) {
-      Timber.e(e, "Failed to load image: IO error")
-      setErrorImage(view)
-    } catch (e: IllegalArgumentException) {
-      Timber.e(e, "Failed to load image: Invalid arguments")
-      setErrorImage(view)
-    }
+    val dm = view.resources.displayMetrics
+    val targetW = (if (view.width > 0) view.width else dm.widthPixels / 2).coerceAtMost(2048)
+    val targetH = (if (view.height > 0) view.height else dm.heightPixels / 2).coerceAtMost(2048)
```
Comment (shobhitagarwal1612) [inline app/src/main/java/org/groundplatform/android/ui/common/BindingAdapters.kt]: Please consider adding a comment to explain why we are downsampling the image.

**Review by shobhitagarwal1612 — APPROVED** [review]
