### PR TITLE
Fix crash in photo fragment when rotating the device and allow selecting a photo from gallery

### LINKED ISSUE #1792: [Data collection] Allow user to "choose photo from library" on photo tasks

### LINKED ISSUE #2323: App crashes when rotating photo task fragment

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Fixes #1792
Fixes #2323

Fix crash in photo fragment due to binding registerForActivityResult outside of onCreate/onAttach.

Also adds support for selecting a photo from gallery (as per figma mocks)

@gino-m  PTAL?

### CODE REVIEW

**Comment by shobhitagarwal1612** [comment]
This PR broke the unit tests. Marking the PR as not ready.

File: ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/photo/PhotoTaskFragment.kt [hunk 1]
```diff
@@ -63,8 +63,16 @@ class PhotoTaskFragment : AbstractTaskFragment<PhotoTaskViewModel>() {
   @Inject lateinit var popups: EphemeralPopups
   @Inject lateinit var navigator: Navigator
 
-  private lateinit var selectPhotoLauncher: ActivityResultLauncher<String>
-  private lateinit var capturePhotoLauncher: ActivityResultLauncher<Uri>
+  private var selectPhotoLauncher: ActivityResultLauncher<String> =
+    registerForActivityResult(ActivityResultContracts.GetContent()) { uri: Uri? ->
```
Comment (gino-m) [inline ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/photo/PhotoTaskFragment.kt:67]: `registerForActivityResult` is neat! We can probably get rid of `ActivityStreams` altogether at some point.

**Review by gino-m — APPROVED** [review]
🎖️ Fine job, @shobhitagarwal1612
