### PR TITLE
[Map] Fix broken add feature button

### LINKED ISSUE #965: [Add point] Add feature fab not shown even though project contains editable layer
Internal test project ID `OPcfIlYMDy8MmV7jDaJX`, layer `vxzSK7sgoRqKBvRexMv7`

### PR DESCRIPTION
**Pull request by gino-m**
Fixes #965:

- [ ] Uses correct string values for `contributorsCanAdd` permissions.
- [ ] Restores add feature button callback accidentally removed while merging with upstream in #871.

Also does some minor cleanup.

@scolsen or @shobhitagarwal1612 PTAL?

### CODE REVIEW

File: gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/LayerEntity.java [hunk 1]
```diff
@@ -92,22 +93,31 @@ static Layer toLayer(LayerEntityAndRelations layerEntityAndRelations) {
...
+        builder.add(toFeatureType(value));
       }
     }
     return builder.build();
   }
 
+  private static FeatureType toFeatureType(String stringValue) {
+    switch (stringValue) {
+      case "points":
+        return FeatureType.POINT;
```
Comment (shobhitagarwal1612) [inline gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/LayerEntity.java:115]: It would be simpler to convert string -> enum using `toEnum()` if both stringValue and Enum were either "point" or "points".

File: gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/LayerConverter.java [hunk 2]
```diff
@@ -40,12 +43,25 @@ static Layer toLayer(String id, LayerNestedObject obj) {
...
     return layer.build();
   }
 
+  private static FeatureType toFeatureType(String stringValue) {
+    switch (stringValue) {
+      case "points":
+        return FeatureType.POINT;
+      default:
+        return FeatureType.UNKNOWN;
+    }
```
Comment (shobhitagarwal1612) [inline gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/LayerConverter.java:62]: Same as above

File: gnd/src/main/res/layout/map_home_layout.xml [hunk 3]
```diff
@@ -61,45 +61,50 @@
...
       android:layout_height="wrap_content"
       android:onClick="@{() -> homeScreenViewModel.openNavDrawer()}"
       android:src="@drawable/ic_menu_black_24dp"
-      app:tint="@{viewModel.getIconTint()}"
       app:backgroundTint="@color/colorBackground"
-      app:layout_constraintStart_toStartOf="parent"
       app:fabSize="mini"
+      app:layout_constraintStart_toStartOf="parent"
       app:layout_constraintTop_toTopOf="parent"
+      app:tint="@{viewModel.getIconTint()}"
```
Comment (shobhitagarwal1612) [inline gnd/src/main/res/layout/map_home_layout.xml:107]: We should use color value rather than `getIconTint`. This gets changed with location lock state

**Review by shobhitagarwal1612 — APPROVED** [review]

File: gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/LayerEntity.java (hunk 1 above)
Comment (gino-m) [reply gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/LayerEntity.java:115]: It would be less code, but without making the mapping explicit, a rename of the enum would break the code. Ideally the enum values should be named for what's more readable in code, and the values in the db for whatever makes most sense there. Coupling them could force a compromise on either end.

File: gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/LayerConverter.java (hunk 2 above)
Comment (gino-m) [reply gnd/src/main/java/com/google/android/gnd/persistence/remote/firestore/schema/LayerConverter.java:62]: See previous comment. If you feel strongly about it please let's discuss!

File: gnd/src/main/res/layout/map_home_layout.xml (hunk 3 above)
Comment (shobhitagarwal1612) [reply gnd/src/main/res/layout/map_home_layout.xml:107]: `getIconTint` supplies the color based on location lock state (i.e. blue if active, else gray)
Hamburger icon shouldn't change its tintColor.

So, I was referring to replacing it with `app:tint="@color/some_color"`
