### PR TITLE
Job: Handle unknown tasks

### LINKED ISSUE #2179: Error when sync: Unknown task id
Sometimes, when "History and sync status" is selected. After that the app crashes.

```
13:03:31.689  E  FATAL EXCEPTION: main
                 Process: com.google.android.ground, PID: 5611
                 java.lang.IllegalStateException: Unknown task id BSfYEdtkHN94U9XcsVY0
                 	at com.google.android.ground.model.job.Job.getTask(Job.kt:36)
                 	at com.google.android.ground.persistence.local.room.converter.SubmissionDeltasConverter.fromString(SubmissionDeltasConverter.kt:67)
                 	at com.google.android.ground.persistence.local.room.converter.ConverterExtKt.toModelObject(ConverterExt.kt:336)
                 	at com.google.android.ground.persistence.local.room.stores.RoomSubmissionStore$getAllSurveyMutationsFlow$$inlined$map$1$2.emit(Emitters.kt:224)
                 	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
                 	at kotlinx.coroutines.flow.internal.SafeCollectorKt$emitFun$1.invoke(SafeCollector.kt:15)
                 	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:87)
                 	at kotlinx.coroutines.flow.internal.SafeCollector.emit(SafeCollector.kt:66)
                 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.emitAllImpl$FlowKt__ChannelsKt(Channels.kt:37)
                 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt.access$emitAllImpl$FlowKt__ChannelsKt(Channels.kt:1)
                 	at kotlinx.coroutines.flow.FlowKt__ChannelsKt$emitAllImpl$1.invokeSuspend(Unknown Source:14)
                 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                 	at android.os.Handler.handleCallback(Handler.java:958)
                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                 	at android.os.Looper.loopOnce(Looper.java:205)
                 	at android.os.Looper.loop(Looper.java:294)
                 	at android.app.ActivityThread.main(ActivityThread.java:8177)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
                 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@9ae6c7c, Dispatchers.Main.immediate]
```

### PR DESCRIPTION
**Pull request by scolsen**
This commit adds a specific exception type for the case in which a caller attempts to retrieve a task from a Job that does not contain a task with the designated ID.

Updates callsites to properly handle and log this exception (in all cases we just ignore the data).

Fixes #2179

### CODE REVIEW

File: ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/SubmissionConverter.kt [hunk 1]
```diff
@@ -85,18 +85,23 @@ internal object SubmissionConverter {
...
-      Task.Type.MULTIPLE_CHOICE -> putMultipleChoiceResponse(taskId, task.multipleChoice, obj, data)
-      Task.Type.NUMBER -> putNumberResponse(taskId, obj, data)
-      Task.Type.DATE -> putDateResponse(taskId, obj, data)
-      Task.Type.TIME -> putTimeResponse(taskId, obj, data)
-      Task.Type.DROP_PIN -> putDropPinTaskResult(taskId, obj, data)
-      Task.Type.DRAW_AREA -> putDrawAreaTaskResult(taskId, obj, data)
-      Task.Type.CAPTURE_LOCATION -> putCaptureLocationResult(taskId, obj, data)
-      else -> throw DataStoreException("Unknown type " + task.type)
+    try {
+      val task = job.getTask(taskId)
```
Comment (gino-m) [inline ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/SubmissionConverter.kt:89]: Generally, we propagate "not found" by returning `null`. Any reason not to do that here? It would also make this code a bit cleaner:

```kt
val task = job.getTask(taskId) ?: return Timber.d(e, "Invalid task ID $taskId")
```

**Review by gino-m — CHANGES_REQUESTED** [review]
Thanks for the fix! See small suggestion!

File: ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/SubmissionConverter.kt (hunk 1 above)
Comment (scolsen) [reply ground/src/main/java/com/google/android/ground/persistence/remote/firebase/schema/SubmissionConverter.kt:89]: I agree that we can probably just return nulls here unless we really think this is an exceptional circumstance,

That said, this would be a significant behavioral change, since callers currently expect this method to return unit and throw exceptions—I'd rather keep this change separate from the fix so I've added an issue and a TODO. Thanks!

https://github.com/google/ground-android/issues/2216
