### PR TITLE
Prevent app crash when offline

### LINKED ISSUE #1666: App crashes when opening in offline mode
Also add unit tests.

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Fixes #1666 

@JSunde @gino-m  PTAL?

### CODE REVIEW

File: ground/src/main/java/com/google/android/ground/repository/TermsOfServiceRepository.kt [hunk 1]
```diff
@@ -35,11 +34,15 @@ constructor(
...
-    get() =
-      remoteDataStore
-        .loadTermsOfService()
-        .timeout(LOAD_REMOTE_SURVEY_TERMS_OF_SERVICE_TIMEOUT_SECS, TimeUnit.SECONDS)
-
   var isTermsOfServiceAccepted: Boolean by localValueStore::isTermsOfServiceAccepted
+
+  suspend fun getTermsOfService(): TermsOfService? =
+    runCatching {
+        // TODO: Maybe parse the exception and display to the user.
```
Comment (JSunde) [inline ground/src/main/java/com/google/android/ground/repository/TermsOfServiceRepository.kt:41]: Should we have a tracking issue for this?

**Review by JSunde — APPROVED** [review]
