### PR TITLE
[Bug] Prevent duplicate entries of multiple choice fields

### LINKED ISSUE #491: Options for multiple choice fields are saved multiple times
Instead of updating existing options in local db, new entries are added each time the project is loaded.

1. Login into app
2. Select `Plastic Frog Finder`
3. Click `Join Project` and change to some other project
4. Change again to `Plastic Frog Finder`

Db snapshot for table option.

1 | 1 | R | Red | lIFrOWC4MrzWDpVPXWjd |  
-- | -- | -- | -- | -- | --
2 | 2 | G | Green | lIFrOWC4MrzWDpVPXWjd |  
3 | 3 | B | Blue | lIFrOWC4MrzWDpVPXWjd |  
4 | 4 | SP | Speckles | iJSrYZRaYZGg25guyM05 |  
5 | 5 | Y | Yellow | lIFrOWC4MrzWDpVPXWjd |  
6 | 6 | ST | Stripes | iJSrYZRaYZGg25guyM05 |  
7 | 7 | DO | Dots | iJSrYZRaYZGg25guyM05 |  
8 | 8 | SM | Smooth | dyGnrwyQXl7dpImkKiNE |  
9 | 9 | BP | Bumpy | dyGnrwyQXl7dpImkKiNE |  
10 | 10 | NT | Not toxic | JKIb8EidOxSuVMryaJSm |  
11 | 11 | ST | Somewhat toxic | JKIb8EidOxSuVMryaJSm |  
12 | 12 | VT | Very toxic | JKIb8EidOxSuVMryaJSm |  
13 | 13 | GJ | Gulab jamun | jIinMHsRu0YCC2sjcjpt |  
14 | 14 | R | Rasgulla | jIinMHsRu0YCC2sjcjpt |  
15 | 15 | L | Ladoo | jIinMHsRu0YCC2sjcjpt |  
16 | 16 | O | Other yum | jIinMHsRu0YCC2sjcjpt |  
17 | 17 | R | Red | lIFrOWC4MrzWDpVPXWjd |  
18 | 18 | G | Green | lIFrOWC4MrzWDpVPXWjd |  
19 | 19 | B | Blue | lIFrOWC4MrzWDpVPXWjd |  
20 | 20 | Y | Yellow | lIFrOWC4MrzWDpVPXWjd |  
21 | 21 | SP | Speckles | iJSrYZRaYZGg25guyM05 |  
22 | 22 | ST | Stripes | iJSrYZRaYZGg25guyM05 |  
23 | 23 | DO | Dots | iJSrYZRaYZGg25guyM05 |  
24 | 24 | SM | Smooth | dyGnrwyQXl7dpImkKiNE |  
25 | 25 | BP | Bumpy | dyGnrwyQXl7dpImkKiNE |  
26 | 26 | NT | Not toxic | JKIb8EidOxSuVMryaJSm |  
27 | 27 | ST | Somewhat toxic | JKIb8EidOxSuVMryaJSm |  
28 | 28 | VT | Very toxic | JKIb8EidOxSuVMryaJSm

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Fixes #491.

Update primary keys for OptionEntity and MultipleChoiceEntity.

Verified by following the steps in issue and confirmed that duplicate entries were not saved.

@gino-m  PTAL?

### CODE REVIEW

File: gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/OptionEntity.java [hunk 1]
```diff
@@ -33,14 +32,12 @@
         @ForeignKey(
             entity = FieldEntity.class,
             parentColumns = "id",
-            childColumns = "field_id",
-            onDelete = ForeignKey.CASCADE),
-    indices = {@Index("field_id")})
+            childColumns = "field_id", // NOPMD
```
Comment (gino-m) [inline gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/OptionEntity.java:35]: Why no PMD?

Comment (shobhitagarwal1612) [reply gnd/src/main/java/com/google/android/gnd/persistence/local/room/entity/OptionEntity.java:35]: The literal "field_id" is used 4 times in the same class. So, PMD recommends converting it into a variable.
