### PR TITLE
Fix integration tests

### LINKED ISSUE #1479: [Code health] Fix instrumentation tests
```
 Test run failed to complete. Instrumentation run failed due to Process crashed.
 Fatal exception
java.lang.RuntimeException: Can't create handler inside thread Thread[DefaultDispatcher-worker-1,5,main] that has not called Looper.prepare()
     FATAL EXCEPTION: DefaultDispatcher-worker-1
Process: com.google.android.ground, PID: 11768
java.lang.RuntimeException: Can't create handler inside thread Thread[DefaultDispatcher-worker-1,5,main] that has not called Looper.prepare()
	at android.os.Handler.<init>(Handler.java:227)
	at android.os.Handler.<init>(Handler.java:129)
	at android.app.Dialog.<init>(Dialog.java:133)
	at android.app.AlertDialog.<init>(AlertDialog.java:204)
	at android.app.AlertDialog.<init>(AlertDialog.java:200)
	at android.app.AlertDialog.<init>(AlertDialog.java:145)
	at android.app.ProgressDialog.<init>(ProgressDialog.java:99)
	at com.google.android.ground.ui.common.ProgressDialogs.modalSpinner(ProgressDialogs.java:29)
	at com.google.android.ground.ui.home.HomeScreenFragment.showSurveyLoadingDialog(HomeScreenFragment.kt:342)
	at com.google.android.ground.ui.home.HomeScreenFragment.onActiveSurveyChange(HomeScreenFragment.kt:302)
	at com.google.android.ground.ui.home.HomeScreenFragment.onCreate$lambda-1(HomeScreenFragment.kt:98)
	at com.google.android.ground.ui.home.HomeScreenFragment.$r8$lambda$XmUiYIXPzXmUNP4rX1uU-0rI2xg(Unknown Source:0)
	at com.google.android.ground.ui.home.HomeScreenFragment$$ExternalSyntheticLambda3.onChanged(Unknown Source:4)
	at androidx.lifecycle.LiveData.considerNotify(LiveData.java:133)
	at androidx.lifecycle.LiveData.dispatchingValue(LiveData.java:151)
	at androidx.lifecycle.LiveData.setValue(LiveData.java:309)
	at androidx.lifecycle.LiveData$1.run(LiveData.java:93)
	at androidx.arch.core.executor.testing.InstantTaskExecutorRule$1.postToMainThread(InstantTaskExecutorRule.java:43)
	at androidx.arch.core.executor.ArchTaskExecutor.postToMainThread(ArchTaskExecutor.java:101)
	at androidx.lifecycle.LiveData.postValue(LiveData.java:293)
	at androidx.lifecycle.LiveDataReactiveStreams$PublisherLiveData$LiveDataSubscriber.onNext(LiveDataReactiveStreams.java:253)
	at io.reactivex.internal.util.HalfSerializer.onNext(HalfSerializer.java:45)
	at io.reactivex.internal.subscribers.StrictSubscriber.onNext(StrictSubscriber.java:97)
	at io.reactivex.processors.BehaviorProcessor$BehaviorSubscription.test(BehaviorProcessor.java:640)
	at io.reactivex.processors.BehaviorProcessor$BehaviorSubscription.emitNext(BehaviorProcessor.java:620)
	at io.reactivex.processors.BehaviorProcessor.onNext(BehaviorProcessor.java:281)
	at com.google.android.ground.repository.SurveyRepository$activateSurvey$1$1.invokeSuspend(SurveyRepository.kt:117)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
	Suppressed: kotlinx.coroutines.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1ddbb39, Dispatchers.Default]
```

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Fixes #1479

MainViewModel gets initialized as soon as the test activity gets created. So, the test never gets a chance to store the survey to local db. Hence the tests were failing when attempting to load survey. To solve this, the flowable now uses Maybe instead of Single.

@gino-m  PTAL?

### CODE REVIEW

**Comment by shobhitagarwal1612** [comment]
Should we also enable instrumentation test for all PRs and not just when pushing to master?

**Comment by gino-m** [comment]
> Should we also enable instrumentation test for all PRs and not just when pushing to master?

Can we create a separate check that fails until we add a specific label, and then runs once the label is added?

File: ground/src/main/java/com/google/android/ground/repository/SurveyRepository.kt [hunk 1]
```diff
@@ -56,13 +57,13 @@ constructor(
...
+   * Emits the currently active survey on subscribe and on change. Emits `empty()`when no survey is
+   * active or local db isn't up-to-date.
    */
   val activeSurvey: @Cold Flowable<Optional<Survey>> =
-    localValueStore.activeSurveyIdFlowable.distinctUntilChanged().switchMapSingle {
-      if (it.isEmpty()) Single.just(Optional.empty())
-      else getOfflineSurvey(it).map { s -> Optional.of(s) }
+    localValueStore.activeSurveyIdFlowable.distinctUntilChanged().switchMapMaybe {
+      if (it.isEmpty()) Maybe.just(Optional.empty())
+      else maybeGetOfflineSurvey(it).map { s -> Optional.of(s) }
```
Comment (gino-m) [inline ground/src/main/java/com/google/android/ground/repository/SurveyRepository.kt:66]: I don't think we need to differentiate null/empty in the method names `maybeGetOfflineSurvey`. Once migrated to coroutines this will just be a suspend fun that returns `Survey?`. Or is there precedent for this?

File: ground/src/main/java/com/google/android/ground/repository/SurveyRepository.kt [hunk 2]
```diff
@@ -78,6 +79,9 @@ constructor(
     return survey
   }
 
+  private fun maybeGetOfflineSurvey(surveyId: String): @Cold Maybe<Survey> =
```
Comment (gino-m) [inline ground/src/main/java/com/google/android/ground/repository/SurveyRepository.kt:82]: I don't think we need to differentiate null/empty in the method names `maybeGetOfflineSurvey`. Once migrated to coroutines this will just be a suspend fun that returns `Survey?`. Or is there precedent for this?

**Review by gino-m — CHANGES_REQUESTED** [review]

**Review by gino-m — APPROVED** [review]
Approved, please consider comment about naming before merging.
