### PR TITLE
Using activeSurveyFlow to make flow async

### LINKED ISSUE #2815: [App Crash] activeSurvey is null
```
 Fatal Exception: java.lang.IllegalArgumentException: Required value was null.
       at com.google.android.ground.ui.datacollection.DataCollectionViewModel.<init>(DataCollectionViewModel.kt:100)
       at com.google.android.ground.DaggerGroundApplication_HiltComponents_SingletonC$ViewModelCImpl$SwitchingProvider.get(DaggerGroundApplication_HiltComponents_SingletonC.java:1465)
       at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory$2.createViewModel(HiltViewModelFactory.java:132)
       at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory$2.create(HiltViewModelFactory.java:103)
       at dagger.hilt.android.internal.lifecycle.HiltViewModelFactory.create(HiltViewModelFactory.java:170)
       at androidx.lifecycle.ViewModelProvider$Factory.create(ViewModelProvider.android.kt:158)
       at androidx.lifecycle.viewmodel.ViewModelProviderImpl_androidKt.createViewModel(ViewModelProviderImpl.android.kt:34)
       at androidx.lifecycle.viewmodel.ViewModelProviderImpl.getViewModel$lifecycle_viewmodel_release(ViewModelProviderImpl.kt:65)
       at androidx.lifecycle.viewmodel.ViewModelProviderImpl.getViewModel$lifecycle_viewmodel_release$default(ViewModelProviderImpl.kt:47)
       at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.android.kt:91)
       at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:51)
       at androidx.lifecycle.ViewModelLazy.getValue(ViewModelLazy.kt:35)
       at com.google.android.ground.ui.datacollection.DataCollectionFragment.getViewModel(DataCollectionFragment.kt:55)
       at com.google.android.ground.ui.datacollection.DataCollectionFragment.onViewCreated(DataCollectionFragment.kt:86)
       at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3152)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:608)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:286)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1675)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3259)
       at androidx.fragment.app.FragmentManager.dispatchViewCreated(FragmentManager.java:3170)
       at androidx.fragment.app.Fragment.performViewCreated(Fragment.java:3153)
       at androidx.fragment.app.FragmentStateManager.createView(FragmentStateManager.java:608)
       at androidx.fragment.app.FragmentStateManager.moveToExpectedState(FragmentStateManager.java:286)
       at androidx.fragment.app.FragmentStore.moveToExpectedState(FragmentStore.java:114)
       at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1675)
       at androidx.fragment.app.FragmentManager.dispatchStateChange(FragmentManager.java:3259)
       at androidx.fragment.app.FragmentManager.dispatchActivityCreated(FragmentManager.java:3177)
       at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:263)
       at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:350)
       at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:251)
       at com.google.android.ground.AbstractActivity.onStart(AbstractActivity.kt:53)
       at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1455)
       at android.app.Activity.performStart(Activity.java:8105)
       at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3745)
       at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:222)
       at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:202)
       at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:174)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:98)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2289)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:201)
       at android.os.Looper.loop(Looper.java:288)
       at android.app.ActivityThread.main(ActivityThread.java:7996)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:553)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
        
```

### PR DESCRIPTION
**Pull request by anandwana001**
Fixes #2815 

@shobhitagarwal1612  PTAL?

### CODE REVIEW

**Comment by shobhitagarwal1612** [comment]
Won't this change now start failing to get the `job` as survey is null?

**Comment by anandwana001** [comment]
> Won't this change now start failing to get the `job` as survey is null?

Should we make the job as a flow too?

**Comment by shobhitagarwal1612** [comment]
The question remains the same, will that pass on the error to the next item or will it stabilize the screen when survey is null?

File: ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt [hunk 1]
```diff
@@ -97,8 +98,15 @@ internal constructor(
   private var shouldLoadFromDraft: Boolean = savedStateHandle[TASK_SHOULD_LOAD_FROM_DRAFT] ?: false
   private var draftDeltas: List<ValueDelta>? = null
 
-  private val activeSurvey: Survey = requireNotNull(surveyRepository.activeSurvey)
-  private val job: Job = activeSurvey.getJob(jobId) ?: error("couldn't retrieve job for $jobId")
+  private val _activeSurvey = MutableStateFlow<Survey?>(null)
+  val activeSurvey = _activeSurvey.asStateFlow()
+
+  init {
+    viewModelScope.launch { surveyRepository.activeSurveyFlow.collect { _activeSurvey.value = it } }
```
Comment (gino-m) [inline ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt:105]: Isn't `activeSurvey` as you're defining it here functionally equivalent to `surveyRepository.activeSurveyFlow`? If so, why not just expose that instead?

File: ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt [hunk 2]
```diff
@@ -97,8 +98,15 @@ internal constructor(
   private var shouldLoadFromDraft: Boolean = savedStateHandle[TASK_SHOULD_LOAD_FROM_DRAFT] ?: false
   private var draftDeltas: List<ValueDelta>? = null
 
-  private val activeSurvey: Survey = requireNotNull(surveyRepository.activeSurvey)
-  private val job: Job = activeSurvey.getJob(jobId) ?: error("couldn't retrieve job for $jobId")
+  private val _activeSurvey = MutableStateFlow<Survey?>(null)
+  val activeSurvey = _activeSurvey.asStateFlow()
```
Comment (gino-m) [inline ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt:102]: Did you mean for this to be make public? I don't see a use anywhere else.

File: ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt [hunk 3]
```diff
@@ -97,8 +98,15 @@ internal constructor(
...
+
+  init {
+    viewModelScope.launch { surveyRepository.activeSurveyFlow.collect { _activeSurvey.value = it } }
+  }
+
+  private val job: Job =
+    activeSurvey.value?.getJob(jobId) ?: error("couldn't retrieve job for $jobId")
```
Comment (gino-m) [inline ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt:109]: Calling `.value` here will grab a snapshot of the current survey at the time this VM is initialized. How is that different from what we're doing already?

**Review by gino-m — DISMISSED** [review]

File: ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt [hunk 4]
```diff
@@ -97,7 +100,10 @@ internal constructor(
   private var shouldLoadFromDraft: Boolean = savedStateHandle[TASK_SHOULD_LOAD_FROM_DRAFT] ?: false
   private var draftDeltas: List<ValueDelta>? = null
 
-  private val activeSurvey: Survey = requireNotNull(surveyRepository.activeSurvey)
+  private val activeSurvey: Survey = runBlocking {
+    surveyRepository.activeSurveyFlow.filterNotNull().first()
+  }
```
Comment (shobhitagarwal1612) [inline ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt:105]: What will happen if the coroutine is never completed? Will the app freeze until ANR error occurs?

Comment (gino-m) [reply ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt:105]: During the standup today, @anandwana001 suggested adding a timeout here. @gino-m I suggested that we allow the timeout exception to propagate and crash the app, since not being able to load the survey from the local db would be an unrecoverable error. 

Ideally, we would ensure the survey was active *before* rendering the `DataCollectionFragment`. We could then use `SurveyRepository.activeSurvey` directly rather than the Flow to get the current survey. @shobhitagarwal1612 Is this possible, based on how the fragment gets activated?

Comment (shobhitagarwal1612) [reply ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt:105]: > Ideally, we would ensure the survey was active before rendering the DataCollectionFragment. We could then use SurveyRepository.activeSurvey directly rather than the Flow to get the current survey. @shobhitagarwal1612 Is this possible, based on how the fragment gets activated?

I don't think so, the fragment gets restored when the activity is started and the injected dependencies are initialized  after the fragment is created.

Comment (gino-m) [reply ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt:105]: > I don't think so, the fragment gets restored when the activity is started and the injected dependencies are initialized after the fragment is created.

On configuration change, yes, but on app restart we explicitly redirect to this fragment if there's an unsaved draft, no? On configuration change the VM should still exist, so this wouldn't be an issue. In `HomeScreenFragment.onViewCreated`, however, we navigate to the data collection screen if there's an unsaved draft.

That said, I agree it would be more robust for the fragment which needs the survey to handle the edge cases, rather than the navigation source. 

@anandwana001  Let's keep the fix in this PR plus timeout as a workaround, we can add other handle delayed load and other edge cases if it turns out to be an issue.

File: ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt [hunk 5]
```diff
@@ -101,7 +102,7 @@ internal constructor(
   private var draftDeltas: List<ValueDelta>? = null
 
   private val activeSurvey: Survey = runBlocking {
-    surveyRepository.activeSurveyFlow.filterNotNull().first()
+    withTimeout(3000L) { surveyRepository.activeSurveyFlow.filterNotNull().first() }
```
Comment (gino-m) [inline ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt:105]: Please move to constant, eg `SURVEY_LOAD_TIMEOUT_MILLIS`

**Comment by shobhitagarwal1612** [comment]
@anandwana001 Please let me know once the comments and conflicts are resolved.

**Review by shobhitagarwal1612 — APPROVED** [review]
