### PR TITLE
[Map] Fix NPE when rotating screen after selecting map type

### LINKED ISSUE #550: App force quits after downloading offline areas
Repro TBD...

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Fixes #550 

* Move subscription for clicks from onViewCreated() to onMapReady()
* Replace MutableLiveData with a PublishSubject to debounce clicks faster than 250ms

@gino-m  PTAL?

### CODE REVIEW

File: gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerFragment.java [hunk 1]
```diff
@@ -163,6 +146,24 @@ private void onMapReady(MapAdapter map) {
     binding.moveFeature.cancelButton.setOnClickListener(__ -> setDefaultMode());
     enableLocationLockBtn();
     mapContainerViewModel.getMbtilesFilePaths().observe(this, map::addTileOverlays);
+    mapContainerViewModel.getSelectMapTypeClicks()
+        .as(autoDisposable(getViewLifecycleOwner()))
```
Comment (shobhitagarwal1612) [inline gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerFragment.java:150]: I also considered using a flowable processor which converts events to LiveData. But the problem with that is, it always emits the last value on resubscription. So, the dialog would pop-up again and again after every rotation (or any config change).

File: gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerViewModel.java [hunk 2]
```diff
@@ -300,8 +305,8 @@ public void setSelectedFeature(Optional<Feature> selectedFeature) {
 
   static class CameraUpdate {
 
-    private Point center;
-    private Optional<Float> minZoomLevel;
+    private final Point center;
+    private final Optional<Float> minZoomLevel;
```
Comment (shobhitagarwal1612) [inline gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerViewModel.java:309]: These changes were unintentional. IDE added these after running "reformat file".

File: gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerFragment.java (hunk 1 above)
Comment (gino-m) [reply gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerFragment.java:152]: That shouldn't be the case; Flowables would only emit the last item if you use buffer strategy "latest". I think this is the most likely cause, since `selectMapTypeClicks` is a `PublishSubject`, which doesn't cache the last value.

If you're still having trouble with duplicate requests, consider using `com.google.android.gnd.rx.Event` to wrap the value, and only processing it using its `ifUnhandled()` method.

File: gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerViewModel.java (hunk 2 above)
Comment (gino-m) [reply gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerViewModel.java:309]: Ok

**Review by gino-m — CHANGES_REQUESTED** [review]
Response to your comment, otherwise LGTM.

File: gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerFragment.java (hunk 1 above)
Comment (shobhitagarwal1612) [reply gnd/src/main/java/com/google/android/gnd/ui/home/mapcontainer/MapContainerFragment.java]: Done

**Review by gino-m — APPROVED** [review]
@shobhitagarwal1612 Force push makes incremental review impossible, and erases the thought process that went into getting where we are. Please avoid rewriting history and use normal push instead! 👍 

Thanks for the changes, looks good!
