### PR TITLE
[MainActivity] Fix Deeplink for both cases, With/Without Activated Survey

### LINKED ISSUE #3176: [Open via link] QR/link doesn't work after removing survey
@rfontanarosa for repro details, @anandwana001 for fix.

### PR DESCRIPTION
**Pull request by anandwana001**
Fixes #3176 

@rfontanarosa @shobhitagarwal1612  PTAL?

### CODE REVIEW

File: app/src/main/java/org/groundplatform/android/MainViewModel.kt [hunk 1]
```diff
@@ -63,6 +69,10 @@ constructor(
   /** The window insets determined by the activity. */
   val windowInsets: MutableLiveData<WindowInsetsCompat> = MutableLiveData()
 
+  private val _deepLinkUri = MutableStateFlow<Uri?>(null)
+  val isDeepLinkAvailable =
```
Comment (shobhitagarwal1612) [inline app/src/main/java/org/groundplatform/android/MainViewModel.kt]: Is this unused?

File: app/src/main/java/org/groundplatform/android/MainViewModel.kt [hunk 2]
```diff
@@ -78,6 +88,12 @@ constructor(
     }
   }
 
+  fun isDeepLinkAvailable(): Boolean = _deepLinkUri.value != null
```
Comment (shobhitagarwal1612) [inline app/src/main/java/org/groundplatform/android/MainViewModel.kt]: This can be declared as private or inlined.

File: app/src/main/java/org/groundplatform/android/MainViewModel.kt [hunk 3]
```diff
@@ -126,6 +142,18 @@ constructor(
       userRepository.saveUserDetails(user)
       if (!isTosAccepted()) {
         MainUiState.TosNotAccepted
+      } else if (isDeepLinkAvailable()) {
+        val deepLinkUri = _deepLinkUri.value
+        val surveyId =
+          deepLinkUri
+            ?.takeIf { it.pathSegments.firstOrNull() == SURVEY_PATH_SEGMENT }
```
Comment (shobhitagarwal1612) [inline app/src/main/java/org/groundplatform/android/MainViewModel.kt:144]: Let's move the logic of parsing survey id from uri to a separate method for readability

File: app/src/main/java/org/groundplatform/android/MainViewModel.kt [hunk 4]
```diff
@@ -126,6 +142,18 @@ constructor(
...
+            ?.lastPathSegment
+
+        if (!surveyId.isNullOrBlank()) {
+          MainUiState.ActiveSurveyById(surveyId)
+        } else {
+          MainUiState.NoActiveSurvey
```
Comment (shobhitagarwal1612) [inline app/src/main/java/org/groundplatform/android/MainViewModel.kt:150]: Should we also log an error with the uri?

Comment (anandwana001) [reply app/src/main/java/org/groundplatform/android/MainViewModel.kt:150]: not an error
