### PR TITLE
Fixed Center point disappears during polygon-drawing

### LINKED ISSUE #3225: Center point disappears during polygon-drawing
When drawing a polygon, after having registered the first corner, the center point (orange plus) disappears. It only reappears when dragging the map and lifting the finger. That behavior created much confusion in the field. Instead, the center point should always remain visible when dragging. Ideally the line between the previous corner and the center point should elongate dynamically while dragging the map.

Only happens after the first corner.

https://github.com/user-attachments/assets/59b3bad6-4a02-45ba-8958-fddd9dc22a86

@gino-m @kenstershiro @shobhitagarwal1612 @anandwana001

### PR DESCRIPTION
**Pull request by anandwana001**
Fixes #3225 

https://github.com/user-attachments/assets/3d6f8131-5db8-4f03-8b12-23bd862d2c03

@jo-spek  @shobhitagarwal1612  PTAL?

### CODE REVIEW

File: app/src/test/java/org/groundplatform/android/ui/datacollection/tasks/polygon/DrawAreaTaskViewModelTest.kt [hunk 1]
```diff
@@ -321,6 +321,72 @@ class DrawAreaTaskViewModelTest : BaseHiltTest() {
...
+    // The helper `updateLastVertex` uses:
+    // val distanceInPixels = if (isNearFirstVertex) threshold else threshold + 1
+    // viewModel.updateLastVertexAndMaybeCompletePolygon(coordinate) { _, _ -> distanceInPixels }
+
+    // If we want `isTooClose` to be true, we need distance <= threshold.
+    // So we should pass `isNearFirstVertex = true` to `updateLastVertex` which sets distance =
+    // threshold.
+    // But `isNearFirstVertex` in helper is intended for "close to first vertex" logic (closing
+    // polygon).
+    // However, the callback is used for both checks.
```
Comment (shobhitagarwal1612) [inline app/src/test/java/org/groundplatform/android/ui/datacollection/tasks/polygon/DrawAreaTaskViewModelTest.kt]: Thanks for the detailed description. Can we summarize this into 1-3 lines only?

Comment (anandwana001) [reply app/src/test/java/org/groundplatform/android/ui/datacollection/tasks/polygon/DrawAreaTaskViewModelTest.kt]: done

**Comment by jo-spek** [comment]
> Fixes #3225
> Screen.Recording.2025-12-02.at.11.41.56.PM.mov
> 
> @jo-spek @shobhitagarwal1612 PTAL?

Hi Akshay, in the video it looks like nothing happened at all when you clicked "Add point" the first time and polygon-drawing only starts after clicking the second time? Am I missing something?

**Comment by anandwana001** [comment]
it is the old behaviour,
user tap add point -> vibrate and then drag tart the line will come 
After add point click the marker is not hiding now, thisis what we fixed here.
@jo-spek

**Comment by jo-spek** [comment]
> it is the old behaviour, user tap add point -> vibrate and then drag tart the line will come After add point click the marker is not hiding now, thisis what we fixed here. @jo-spek

What I saw in the video is not really what users would expect. The first time you click "Add point" nothing happens at all. Mistake in the recording?

**Comment by jo-spek** [comment]
Hi @anandwana001, thanks for the updated recording. It shows the problem that I initially suggested to fix. When clicking "Add point" the first time, the orange plus should transform into the white+orange circle as a visual feedback that a point has been created. Exactly as happens for all the following points.

**Comment by anandwana001** [comment]
@jo-spek Got it, I think it is more like a feature, not a bug, as it is not there earlier. Let me update in this PR only. 
cc @gino-m

**Comment by jo-spek** [comment]
> @jo-spek Got it, I think it is more like a feature, not a bug, as it is not there earlier. Let me update in this PR only. cc @gino-m

Newest video re-upload is exactly what I was looking for! Seems like there is a tiny rendering issue or is that the video quality? Looks a bit like there are two circles on top of each other. But let's stick to if for the moment. I'll ask @rfontanarosa for a new APK and will give it a try ASAP.

**Comment by anandwana001** [comment]
@jo-spek any update on this?

**Comment by jo-spek** [comment]
> @jo-spek any update on this?

Looks great! We can close this one!

File: app/src/main/java/org/groundplatform/android/ui/map/gms/features/LineStringRenderer.kt [hunk 2]
```diff
@@ -58,11 +58,17 @@ constructor(
...
+    val options = PolylineOptions().clickable(false)
+    val coordinates = geometry.coordinates.toLatLngList()
+    if (coordinates.size > 1 && coordinates.all { it == coordinates[0] }) {
+      // If all points are identical, we add a tiny offset to the last point to ensure the
+      // polyline has non-zero length.
+      options.addAll(coordinates.dropLast(1))
+      options.add(coordinates.last().addOffset())
+    } else {
+      options.addAll(coordinates)
+    }
```
Comment (shobhitagarwal1612) [inline app/src/main/java/org/groundplatform/android/ui/map/gms/features/LineStringRenderer.kt]: Can we refactor the logic for converting coordinates to a list of latLng to a new function? This would help with readability as well.

File: app/src/main/java/org/groundplatform/android/ui/map/gms/features/LineStringRenderer.kt [hunk 3]
```diff
@@ -80,7 +86,12 @@ constructor(
     geometry: LineString,
     tooltipText: String?,
   ) {
-    mapFeature.points = geometry.coordinates.toLatLngList()
+    val coordinates = geometry.coordinates.toLatLngList()
+    if (coordinates.size > 1 && coordinates.all { it == coordinates[0] }) {
+      mapFeature.points = coordinates.dropLast(1) + coordinates.last().addOffset()
+    } else {
+      mapFeature.points = coordinates
```
Comment (shobhitagarwal1612) [inline app/src/main/java/org/groundplatform/android/ui/map/gms/features/LineStringRenderer.kt]: Same as previous comment, let's separate out the logic to a different method to help with readability.

File: app/src/main/java/org/groundplatform/android/ui/map/gms/features/LineStringRenderer.kt [hunk 4]
```diff
@@ -108,4 +107,20 @@ constructor(
...
+
+  private fun processCoordinates(geometry: LineString): List<LatLng> {
+    val coordinates = geometry.coordinates.toLatLngList()
+    // If all points are identical, we add a tiny offset to the last point to ensure the
+    // polyline has non-zero length.
+    if (coordinates.size > 1 && coordinates.all { it == coordinates[0] }) {
+      return coordinates.dropLast(1) + coordinates.last().addOffset()
+    }
+    return coordinates
+  }
```
Comment (shobhitagarwal1612) [inline app/src/main/java/org/groundplatform/android/ui/map/gms/features/LineStringRenderer.kt]: Just to confirm, this is only possible when the size is 2 and both are same, right? In that case, let's update the condition to reflect the same.

Also, let's update the method name to better reflect the purpose (e.g.  `convertMaybeAddOffsetPoint`)

File: app/src/test/java/org/groundplatform/android/ui/datacollection/tasks/polygon/DrawAreaTaskViewModelTest.kt [hunk 5]
```diff
@@ -321,6 +321,58 @@ class DrawAreaTaskViewModelTest : BaseHiltTest() {
...
+    updateLastVertexAndAdd(COORDINATE_2)
+
+    // Distance between COORDINATE_2 (10, 10) and COORDINATE_3 (20, 20) is ~14.14
+    // Threshold is 24. So this should be too close.
+    updateLastVertex(COORDINATE_3, isNearFirstVertex = false)
+    // This test checks that isTooClose becomes true when the last two vertices are within the
+    // distance threshold. It manually triggers the update with a controlled distance equal
+    // to the threshold to verify the behavior.
+
+    // Let's manually call updateLastVertexAndMaybeCompletePolygon to be explicit.
```
Comment (shobhitagarwal1612) [inline app/src/test/java/org/groundplatform/android/ui/datacollection/tasks/polygon/DrawAreaTaskViewModelTest.kt]: Please cleanup debug only comments.

File: app/src/test/java/org/groundplatform/android/ui/datacollection/tasks/polygon/DrawAreaTaskViewModelTest.kt [hunk 6]
```diff
@@ -321,6 +321,58 @@ class DrawAreaTaskViewModelTest : BaseHiltTest() {
...
+  fun `isTooClose is true when last vertex is close to previous vertex`() {
+    updateLastVertexAndAdd(COORDINATE_1)
+    updateLastVertexAndAdd(COORDINATE_2)
+
+    // Distance between COORDINATE_2 (10, 10) and COORDINATE_3 (20, 20) is ~14.14
+    // Threshold is 24. So this should be too close.
+    updateLastVertex(COORDINATE_3, isNearFirstVertex = false)
+    // This test checks that isTooClose becomes true when the last two vertices are within the
+    // distance threshold. It manually triggers the update with a controlled distance equal
+    // to the threshold to verify the behavior.
```
Comment (shobhitagarwal1612) [inline app/src/test/java/org/groundplatform/android/ui/datacollection/tasks/polygon/DrawAreaTaskViewModelTest.kt]: This is already implicit from the test name.
