### PR TITLE
Fix crash in data collection fragment

### LINKED ISSUE #2408: [Bug] App crash in data collection screen
Issue reported via crashlytics

Exception message:  `Fatal Exception: java.util.NoSuchElementException:  List is empty`

Stacktrace:

```
com.google.android.ground.ui.datacollection.DataCollectionViewModel.<init> (DataCollectionViewModel.kt:136)
com.google.android.ground.DaggerGroundApplication_HiltComponents_SingletonC$ViewModelCImpl$SwitchingProvider.get (DaggerGroundApplication_HiltComponents_SingletonC.java:1480)
dagger.hilt.android.internal.lifecycle.HiltViewModelFactory$2.createViewModel (HiltViewModelFactory.java:132)
dagger.hilt.android.internal.lifecycle.HiltViewModelFactory$2.create (HiltViewModelFactory.java:103)
dagger.hilt.android.internal.lifecycle.HiltViewModelFactory.create (HiltViewModelFactory.java:170)
androidx.lifecycle.ViewModelProvider.get (ViewModelProvider.kt:184)
```

The above stacktrace points to code below:

```
var currentTaskId: StateFlow<String> =
    savedStateHandle.getStateFlow(TASK_POSITION_ID, tasks.first().id)
```

`first()` expects the list to be non-empty and throws an exception. Handling that should atleast prevent the crash from happening.

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Fixes #2408

Instead of crashing the app, reset the current task id to empty. 

@gino-m @sufyanAbbasi  PTAL?

### CODE REVIEW

File: ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt [hunk 1]
```diff
@@ -133,7 +133,7 @@ internal constructor(
 
   // Tracks the current task ID to compute the position in the list of tasks for the current job.
   var currentTaskId: StateFlow<String> =
-    savedStateHandle.getStateFlow(TASK_POSITION_ID, tasks.first().id)
+    savedStateHandle.getStateFlow(TASK_POSITION_ID, tasks.firstOrNull()?.id ?: "")
```
Comment (gino-m) [inline ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt:136]: Do we need to update anything else to check if taskId is empty?

**Review by gino-m — CHANGES_REQUESTED** [review]

File: ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt (hunk 1 above)
Comment (shobhitagarwal1612) [reply ground/src/main/java/com/google/android/ground/ui/datacollection/DataCollectionViewModel.kt:136]: That is already handled. We use it to check current position and if it's empty, we fallback to first position

**Review by gino-m — APPROVED** [review]
