### PR TITLE
[Data Collection] Update "Next" to "Done" when on last task

### LINKED ISSUE #1982: Data collection task next button labels incorrect
- [x] Label should be "Next" and not "Continue"
- [ ] On last task, button label should be "Done" <--  @amegantz Is that correct?

### PR DESCRIPTION
**Pull request by shobhitagarwal1612**
Fixes #1982

[done_button.webm](https://github.com/google/ground-android/assets/8918023/25d8cd3e-5060-45fe-88b9-dc7c0783e501)

@gino-m  PTAL?

### CODE REVIEW

File: ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/AbstractTaskFragment.kt [hunk 1]
```diff
@@ -145,16 +149,27 @@ abstract class AbstractTaskFragment<T : AbstractTaskViewModel> : AbstractFragmen
...
       )
-    buttons[action] = button
+    buttons[updatedAction] = button
     return button
   }
 
+  /**
+   * Changes the button from "Next" to "Done" if the current task fragment is last in it's position.
+   */
+  private fun maybeOverrideButton(action: ButtonAction): ButtonAction =
```
Comment (gino-m) [inline ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/AbstractTaskFragment.kt:166]: Can this be done reactively / declaratively using data binding rather than programmatically? e.g. by adding LiveData<Boolean> `isLastTask` to the ViewModel?

**Review by gino-m — CHANGES_REQUESTED** [review]
One suggestions, otherwise LG!

File: ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/AbstractTaskFragment.kt (hunk 1 above)
Comment (shobhitagarwal1612) [reply ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/AbstractTaskFragment.kt]: I don't think we can do it reactively or using data binding. We create the layout of the task fragment dynamically

Comment (gino-m) [reply ground/src/main/java/com/google/android/ground/ui/datacollection/tasks/AbstractTaskFragment.kt]: I see. Sgtm!

**Review by gino-m — APPROVED** [review]
